In [26]:
import pandas as pd
import numpy as np
import collections as co
from scipy import stats
import matplotlib.pylab as plt 
%matplotlib inline

In [27]:
# read in all files
fy14_ak = pd.read_csv('fy14_ak.csv')
fy14_al = pd.read_csv('fy14_al.csv')
fy14_ar = pd.read_csv('fy14_ar.csv')
fy14_az = pd.read_csv('fy14_az.csv')
fy14_ca = pd.read_csv('fy14_ca.csv')
fy14_co = pd.read_csv('fy14_co.csv')
fy14_ct = pd.read_csv('fy14_ct.csv')
fy14_dc = pd.read_csv('fy14_dc.csv')
fy14_de = pd.read_csv('fy14_de.csv')
fy14_fl = pd.read_csv('fy14_fl.csv')
fy14_ga = pd.read_csv('fy14_ga.csv')
fy14_gu = pd.read_csv('fy14_gu.csv')
fy14_hi = pd.read_csv('fy14_hi.csv')
fy14_ia = pd.read_csv('fy14_ia.csv')
fy14_id = pd.read_csv('fy14_id.csv')
fy14_il = pd.read_csv('fy14_il.csv')
fy14_in = pd.read_csv('fy14_in.csv')
fy14_ks = pd.read_csv('fy14_ks.csv')
fy14_ky = pd.read_csv('fy14_ky.csv')
fy14_la = pd.read_csv('fy14_la.csv')
fy14_ma = pd.read_csv('fy14_ma.csv')
fy14_md = pd.read_csv('fy14_md.csv')
fy14_me = pd.read_csv('fy14_me.csv')
fy14_mi = pd.read_csv('fy14_mi.csv')
fy14_mn = pd.read_csv('fy14_mn.csv')
fy14_mo = pd.read_csv('fy14_mo.csv')
fy14_ms = pd.read_csv('fy14_ms.csv')
fy14_mt = pd.read_csv('fy14_mt.csv')
fy14_nc = pd.read_csv('fy14_nc.csv')
fy14_nd = pd.read_csv('fy14_nd.csv')
fy14_ne = pd.read_csv('fy14_ne.csv')
fy14_nh = pd.read_csv('fy14_nh.csv')
fy14_nj = pd.read_csv('fy14_nj.csv')
fy14_nm = pd.read_csv('fy14_nm.csv')
fy14_nv = pd.read_csv('fy14_nv.csv')
fy14_ny = pd.read_csv('fy14_ny.csv')
fy14_oh = pd.read_csv('fy14_oh.csv')
fy14_ok = pd.read_csv('fy14_ok.csv')
fy14_or = pd.read_csv('fy14_or.csv')
fy14_pa = pd.read_csv('fy14_pa.csv')
fy14_pr = pd.read_csv('fy14_pr.csv')
fy14_ri = pd.read_csv('fy14_ri.csv')
fy14_sc = pd.read_csv('fy14_sc.csv')
fy14_sd = pd.read_csv('fy14_sd.csv')
fy14_tn = pd.read_csv('fy14_tn.csv')
fy14_tx = pd.read_csv('fy14_tx.csv')
fy14_ut = pd.read_csv('fy14_ut.csv')
fy14_va = pd.read_csv('fy14_va.csv')
fy14_vt = pd.read_csv('fy14_vt.csv')
fy14_wa = pd.read_csv('fy14_wa.csv')
fy14_wi = pd.read_csv('fy14_wi.csv')
fy14_wv = pd.read_csv('fy14_wv.csv')
fy14_wy = pd.read_csv('fy14_wy.csv')

#fy15
fy15_ak = pd.read_csv('fy15_ak.csv')
fy15_al = pd.read_csv('fy15_al.csv')
fy15_ar = pd.read_csv('fy15_ar.csv')
fy15_az = pd.read_csv('fy15_az.csv')
fy15_ca = pd.read_csv('fy15_ca.csv')
fy15_co = pd.read_csv('fy15_co.csv')
fy15_ct = pd.read_csv('fy15_ct.csv')
fy15_dc = pd.read_csv('fy15_dc.csv')
fy15_de = pd.read_csv('fy15_de.csv')
fy15_fl = pd.read_csv('fy15_fl.csv')
fy15_ga = pd.read_csv('fy15_ga.csv')
fy15_gu = pd.read_csv('fy15_gu.csv')
fy15_hi = pd.read_csv('fy15_hi.csv')
fy15_ia = pd.read_csv('fy15_ia.csv')
fy15_id = pd.read_csv('fy15_id.csv')
fy15_il = pd.read_csv('fy15_il.csv')
fy15_in = pd.read_csv('fy15_in.csv')
fy15_ks = pd.read_csv('fy15_ks.csv')
fy15_ky = pd.read_csv('fy15_ky.csv')
fy15_la = pd.read_csv('fy15_la.csv')
fy15_ma = pd.read_csv('fy15_ma.csv')
fy15_md = pd.read_csv('fy15_md.csv')
fy15_me = pd.read_csv('fy15_me.csv')
fy15_mi = pd.read_csv('fy15_mi.csv')
fy15_mn = pd.read_csv('fy15_mn.csv')
fy15_mo = pd.read_csv('fy15_mo.csv')
fy15_ms = pd.read_csv('fy15_ms.csv')
fy15_mt = pd.read_csv('fy15_mt.csv')
fy15_nc = pd.read_csv('fy15_nc.csv')
fy15_nd = pd.read_csv('fy15_nd.csv')
fy15_ne = pd.read_csv('fy15_ne.csv')
fy15_nh = pd.read_csv('fy15_nh.csv')
fy15_nj = pd.read_csv('fy15_nj.csv')
fy15_nm = pd.read_csv('fy15_nm.csv')
fy15_nv = pd.read_csv('fy15_nv.csv')
fy15_ny = pd.read_csv('fy15_ny.csv')
fy15_oh = pd.read_csv('fy15_oh.csv')
fy15_ok = pd.read_csv('fy15_ok.csv')
fy15_or = pd.read_csv('fy15_or.csv')
fy15_pa = pd.read_csv('fy15_pa.csv')
fy15_pr = pd.read_csv('fy15_pr.csv')
fy15_ri = pd.read_csv('fy15_ri.csv')
fy15_sc = pd.read_csv('fy15_sc.csv')
fy15_sd = pd.read_csv('fy15_sd.csv')
fy15_tn = pd.read_csv('fy15_tn.csv')
fy15_tx = pd.read_csv('fy15_tx.csv')
fy15_ut = pd.read_csv('fy15_ut.csv')
fy15_va = pd.read_csv('fy15_va.csv')
fy15_vt = pd.read_csv('fy15_vt.csv')
fy15_wa = pd.read_csv('fy15_wa.csv')
fy15_wi = pd.read_csv('fy15_wi.csv')
fy15_wv = pd.read_csv('fy15_wv.csv')
fy15_wy = pd.read_csv('fy15_wy.csv')

#fy16
fy16_ak = pd.read_csv('fy16_ak.csv')
fy16_al = pd.read_csv('fy16_al.csv')
fy16_ar = pd.read_csv('fy16_ar.csv')
fy16_az = pd.read_csv('fy16_az.csv')
fy16_ca = pd.read_csv('fy16_ca.csv')
fy16_co = pd.read_csv('fy16_co.csv')
fy16_ct = pd.read_csv('fy16_ct.csv')
fy16_dc = pd.read_csv('fy16_dc.csv')
fy16_de = pd.read_csv('fy16_de.csv')
fy16_fl = pd.read_csv('fy16_fl.csv')
fy16_ga = pd.read_csv('fy16_ga.csv')
fy16_gu = pd.read_csv('fy16_gu.csv')
fy16_hi = pd.read_csv('fy16_hi.csv')
fy16_ia = pd.read_csv('fy16_ia.csv')
fy16_id = pd.read_csv('fy16_id.csv')
fy16_il = pd.read_csv('fy16_il.csv')
fy16_in = pd.read_csv('fy16_in.csv')
fy16_ks = pd.read_csv('fy16_ks.csv')
fy16_ky = pd.read_csv('fy16_ky.csv')
fy16_la = pd.read_csv('fy16_la.csv')
fy16_ma = pd.read_csv('fy16_ma.csv')
fy16_md = pd.read_csv('fy16_md.csv')
fy16_me = pd.read_csv('fy16_me.csv')
fy16_mi = pd.read_csv('fy16_mi.csv')
fy16_mn = pd.read_csv('fy16_mn.csv')
fy16_mo = pd.read_csv('fy16_mo.csv')
fy16_ms = pd.read_csv('fy16_ms.csv')
fy16_mt = pd.read_csv('fy16_mt.csv')
fy16_nc = pd.read_csv('fy16_nc.csv')
fy16_nd = pd.read_csv('fy16_nd.csv')
fy16_ne = pd.read_csv('fy16_ne.csv')
fy16_nh = pd.read_csv('fy16_nh.csv')
fy16_nj = pd.read_csv('fy16_nj.csv')
fy16_nm = pd.read_csv('fy16_nm.csv')
fy16_nv = pd.read_csv('fy16_nv.csv')
fy16_ny = pd.read_csv('fy16_ny.csv')
fy16_oh = pd.read_csv('fy16_oh.csv')
fy16_ok = pd.read_csv('fy16_ok.csv')
fy16_or = pd.read_csv('fy16_or.csv')
fy16_pa = pd.read_csv('fy16_pa.csv')
fy16_pr = pd.read_csv('fy16_pr.csv')
fy16_ri = pd.read_csv('fy16_ri.csv')
fy16_sc = pd.read_csv('fy16_sc.csv')
fy16_sd = pd.read_csv('fy16_sd.csv')
fy16_tn = pd.read_csv('fy16_tn.csv')
fy16_tx = pd.read_csv('fy16_tx.csv')
fy16_ut = pd.read_csv('fy16_ut.csv')
fy16_va = pd.read_csv('fy16_va.csv')
fy16_vt = pd.read_csv('fy16_vt.csv')
fy16_wa = pd.read_csv('fy16_wa.csv')
fy16_wi = pd.read_csv('fy16_wi.csv')
fy16_wv = pd.read_csv('fy16_wv.csv')
fy16_wy = pd.read_csv('fy16_wy.csv')

In [28]:
#Generate lists
FY_14_LIST=[
    fy14_ak,fy14_al,fy14_ar,fy14_az,fy14_ca,fy14_co,fy14_ct,fy14_dc,fy14_de,fy14_fl,fy14_ga,fy14_gu,fy14_hi,fy14_ia,
    fy14_id,fy14_il,fy14_in,fy14_ks,fy14_ky,fy14_la,fy14_ma,fy14_md,fy14_me,fy14_mi,fy14_mn,fy14_mo,fy14_ms,fy14_mt,
    fy14_nc,fy14_nd,fy14_ne,fy14_nh,fy14_nj,fy14_nm,fy14_nv,fy14_ny,fy14_oh,fy14_ok,fy14_or,fy14_pa,fy14_pr,fy14_ri,
    fy14_sc,fy14_sd,fy14_tn,fy14_tx,fy14_ut,fy14_va,fy14_vt,fy14_wa,fy14_wi,fy14_wv,fy14_wy
]
FY_15_LIST=[
    fy15_ak,fy15_al,fy15_ar,fy15_az,fy15_ca,fy15_co,fy15_ct,fy15_dc,fy15_de,fy15_fl,fy15_ga,fy15_gu,fy15_hi,fy15_ia,
    fy15_id,fy15_il,fy15_in,fy15_ks,fy15_ky,fy15_la,fy15_ma,fy15_md,fy15_me,fy15_mi,fy15_mn,fy15_mo,fy15_ms,fy15_mt,
    fy15_nc,fy15_nd,fy15_ne,fy15_nh,fy15_nj,fy15_nm,fy15_nv,fy15_ny,fy15_oh,fy15_ok,fy15_or,fy15_pa,fy15_pr,fy15_ri,
    fy15_sc,fy15_sd,fy15_tn,fy15_tx,fy15_ut,fy15_va,fy15_vt,fy15_wa,fy15_wi,fy15_wv,fy15_wy
]
FY_16_LIST=[
    fy16_ak,fy16_al,fy16_ar,fy16_az,fy16_ca,fy16_co,fy16_ct,fy16_dc,fy16_de,fy16_fl,fy16_ga,fy16_gu,fy16_hi,fy16_ia,
    fy16_id,fy16_il,fy16_in,fy16_ks,fy16_ky,fy16_la,fy16_ma,fy16_md,fy16_me,fy16_mi,fy16_mn,fy16_mo,fy16_ms,fy16_mt,
    fy16_nc,fy16_nd,fy16_ne,fy16_nh,fy16_nj,fy16_nm,fy16_nv,fy16_ny,fy16_oh,fy16_ok,fy16_or,fy16_pa,fy16_pr,fy16_ri,
    fy16_sc,fy16_sd,fy16_tn,fy16_tx,fy16_ut,fy16_va,fy16_vt,fy16_wa,fy16_wi,fy16_wv,fy16_wy 
]
ALL_YEARS = [fy14_ak,fy14_al,fy14_ar,fy14_az,fy14_ca,fy14_co,fy14_ct,fy14_dc,fy14_de,fy14_fl,fy14_ga,fy14_gu,fy14_hi,fy14_ia,
    fy14_id,fy14_il,fy14_in,fy14_ks,fy14_ky,fy14_la,fy14_ma,fy14_md,fy14_me,fy14_mi,fy14_mn,fy14_mo,fy14_ms,fy14_mt,
    fy14_nc,fy14_nd,fy14_ne,fy14_nh,fy14_nj,fy14_nm,fy14_nv,fy14_ny,fy14_oh,fy14_ok,fy14_or,fy14_pa,fy14_pr,fy14_ri,
    fy14_sc,fy14_sd,fy14_tn,fy14_tx,fy14_ut,fy14_va,fy14_vt,fy14_wa,fy14_wi,fy14_wv,fy14_wy,fy15_ak,fy15_al,fy15_ar,fy15_az,fy15_ca,fy15_co,fy15_ct,fy15_dc,fy15_de,fy15_fl,fy15_ga,fy15_gu,fy15_hi,fy15_ia,
    fy15_id,fy15_il,fy15_in,fy15_ks,fy15_ky,fy15_la,fy15_ma,fy15_md,fy15_me,fy15_mi,fy15_mn,fy15_mo,fy15_ms,fy15_mt,
    fy15_nc,fy15_nd,fy15_ne,fy15_nh,fy15_nj,fy15_nm,fy15_nv,fy15_ny,fy15_oh,fy15_ok,fy15_or,fy15_pa,fy15_pr,fy15_ri,
    fy15_sc,fy15_sd,fy15_tn,fy15_tx,fy15_ut,fy15_va,fy15_vt,fy15_wa,fy15_wi,fy15_wv,fy15_wy,fy16_ak,fy16_al,fy16_ar,fy16_az,fy16_ca,fy16_co,fy16_ct,fy16_dc,fy16_de,fy16_fl,fy16_ga,fy16_gu,fy16_hi,fy16_ia,
    fy16_id,fy16_il,fy16_in,fy16_ks,fy16_ky,fy16_la,fy16_ma,fy16_md,fy16_me,fy16_mi,fy16_mn,fy16_mo,fy16_ms,fy16_mt,
    fy16_nc,fy16_nd,fy16_ne,fy16_nh,fy16_nj,fy16_nm,fy16_nv,fy16_ny,fy16_oh,fy16_ok,fy16_or,fy16_pa,fy16_pr,fy16_ri,
    fy16_sc,fy16_sd,fy16_tn,fy16_tx,fy16_ut,fy16_va,fy16_vt,fy16_wa,fy16_wi,fy16_wv,fy16_wy]

In [29]:
df = pd.read_excel('VET01.xls',sheetname=None)
#vet01a = df['VET01A']
keys = df.keys()
keys

odict_keys(['VET01A', 'VET01B', 'VET01C', 'VET01D'])

In [30]:
#create dataframes for pages
#co.OrderedDict(sorted(df.items(), key=lambda t: t[0]))
vet01a = df['VET01A'] # VET010180D - VET320200D (Veterans - total 1980 (sample) - Veterans - females 2000 (sample))
vet01b = df['VET01B'] # VET415200D - VET510180D (Veterans by age - total, 18-64 years 2000 (sample) - Nonveterans - total 1980 (sample))
vet01c = df['VET01C'] # VET510190D - VET635209D (Nonveterans - total 1990 (sample) - Veterans by age - males, 75 years and over 2005-2009)
vet01d = df['VET01D'] # VET640209D - VET670209D (Female veterans - percent 2005-2009 - Nonveterans - total 2005-2009)

In [33]:
for item in ALL_YEARS:
    print(item.iloc[:,1:5])
    #item.iloc[:,4] = item.iloc[:,4].astype(float)

   State County/ Congressional District Veteran Population* Total Expenditure
0     AK                 ALEUTIANS EAST                 151             $181
1     AK                 ALEUTIANS WEST                 348             $324
2     AK                      ANCHORAGE              30,240         $285,554
3     AK                         BETHEL                 996           $1,497
4     AK                    BRISTOL BAY                 115             $298
5     AK                         DENALI                 234             $928
6     AK                     DILLINGHAM                 296             $713
7     AK              FAIRBANKS N. STAR              12,665          $80,616
8     AK                         HAINES                 290           $1,000
9     AK                  HOONAH-ANGOON                 197             $806
10    AK                         JUNEAU               2,249          $12,210
11    AK                KENAI PENINSULA               5,509          $40,937
12    AK              KETCHIKAN GATEWAY               1,461           $4,643
13    AK                  KODIAK ISLAND               1,367           $6,078
14    AK             LAKE AND PENINSULA                 117             $249
15    AK              MATANUSKA SUSITNA              10,900          $92,361
16    AK                           NOME                 670             $828
17    AK                    NORTH SLOPE                 348             $715
18    AK               NORTHWEST ARCTIC                 462             $363
19    AK                     PETERSBURG                 402           $1,593
20    AK          PRINCE OF WALES-HYDER                 541           $2,015
21    AK                          SITKA                 795           $2,661
22    AK                        SKAGWAY                  86             $197
23    AK            SOUTHEAST FAIRBANKS                 746           $6,005
24    AK                 VALDEZ CORDOVA               1,078           $5,083
25    AK                   WADE HAMPTON                 278             $943
26    AK                       WRANGELL                 266             $918
27    AK                        YAKUTAT                  79             $362
28    AK                  YUKON KOYUKUK                 511           $2,202
29    AK                ALASKA (Totals)              73,397         $552,280
30    AK                CONG. DIST (01)              73,397         $552,280
31    AK                ALASKA (Totals)              73,397         $552,280
   State County/ Congressional District Veteran Population* Total Expenditure
0     AL                        AUTAUGA               6,019          $49,826
1     AL                        BALDWIN              20,083          $98,756
2     AL                        BARBOUR               2,408          $16,680
3     AL                           BIBB               1,321          $13,728
4     AL                         BLOUNT               4,812          $23,123
5     AL                        BULLOCK                 907           $7,335
6     AL                         BUTLER               1,824          $12,620
7     AL                        CALHOUN              11,922          $91,738
8     AL                       CHAMBERS               3,120          $23,250
9     AL                       CHEROKEE               2,176          $12,350
10    AL                        CHILTON               3,377          $27,428
11    AL                        CHOCTAW                 934          $10,332
12    AL                         CLARKE               1,779          $14,486
13    AL                           CLAY               1,243           $7,265
14    AL                       CLEBURNE                 974           $5,806
15    AL                         COFFEE               7,341          $69,687
16    AL                        COLBERT               4,787          $35,997
17    AL                        CONECUH               1,241          $10,087
18    AL                          COOSA               1,027           $8,415
19    AL                      COVINGTON               3,503          $26,105
20    AL                       CRENSHAW                 937           $9,173
21    AL                        CULLMAN               7,192          $42,224
22    AL                           DALE               7,266          $60,922
23    AL                         DALLAS               2,924          $27,150
24    AL                        DE KALB               4,490          $28,046
25    AL                         ELMORE               9,417          $74,820
26    AL                       ESCAMBIA               3,061          $20,658
27    AL                         ETOWAH               8,998          $67,736
28    AL                        FAYETTE               1,375          $13,327
29    AL                       FRANKLIN               1,838          $12,437
..   ...                            ...                 ...               ...
46    AL                         MARION               2,313          $14,834
47    AL                       MARSHALL               7,370          $42,949
48    AL                         MOBILE              33,066         $221,670
49    AL                         MONROE               1,564          $12,353
50    AL                     MONTGOMERY              19,824         $264,683
51    AL                         MORGAN               9,693          $57,141
52    AL                          PERRY                 729           $7,013
53    AL                        PICKENS               1,557          $17,484
54    AL                           PIKE               2,343          $20,557
55    AL                       RANDOLPH               1,780          $12,381
56    AL                        RUSSELL               5,365          $85,244
57    AL                    SAINT CLAIR               7,853          $43,563
58    AL                         SHELBY              14,579          $80,301
59    AL                         SUMTER                 714           $8,170
60    AL                      TALLADEGA               7,208          $42,451
61    AL                     TALLAPOOSA               3,575          $33,906
62    AL                     TUSCALOOSA              14,151         $147,254
63    AL                         WALKER               5,952          $47,189
64    AL                     WASHINGTON               1,544           $8,172
65    AL                         WILCOX                 626           $6,375
66    AL                        WINSTON               1,883          $12,788
67    AL               ALABAMA (Totals)             413,618       $3,191,317
68    AL                CONG. DIST (01)              59,982         $366,474
69    AL                CONG. DIST (02)              70,790         $637,397
70    AL                CONG. DIST (03)              60,826         $517,511
71    AL                CONG. DIST (04)              54,485         $368,819
72    AL                CONG. DIST (05)              69,268         $398,195
73    AL                CONG. DIST (06)              52,116         $291,684
74    AL                CONG. DIST (07)              46,152         $611,236
75    AL               ALABAMA (Totals)             413,618       $3,191,317

[76 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     AR                       ARKANSAS               1,478          $10,755
1     AR                         ASHLEY               1,682          $12,529
2     AR                         BAXTER               5,599          $34,655
3     AR                         BENTON              19,437         $116,484
4     AR                          BOONE               3,561          $25,454
5     AR                        BRADLEY               1,033           $5,925
6     AR                        CALHOUN                 502           $2,133
7     AR                        CARROLL               2,723          $18,322
8     AR                         CHICOT                 903           $8,478
9     AR                          CLARK               1,637          $13,578
10    AR                           CLAY               1,418          $12,457
11    AR                       CLEBURNE               3,078          $25,192
12    AR                      CLEVELAND                 721           $6,819
13    AR                       COLUMBIA               1,613          $11,912
14    AR                         CONWAY               1,794          $16,748
15    AR                      CRAIGHEAD               7,173          $41,514
16    AR                       CRAWFORD               5,771          $48,135
17    AR                     CRITTENDEN               3,716          $30,840
18    AR                          CROSS               1,111           $9,285
19    AR                         DALLAS                 669           $5,555
20    AR                          DESHA                 996           $8,925
21    AR                           DREW               1,534          $10,339
22    AR                       FAULKNER              10,120          $76,357
23    AR                       FRANKLIN               1,609          $15,333
24    AR                         FULTON               1,175          $10,495
25    AR                        GARLAND              10,297          $84,919
26    AR                          GRANT               1,461          $13,772
27    AR                         GREENE               3,140          $29,248
28    AR                      HEMPSTEAD               1,446          $10,105
29    AR                     HOT SPRING               3,159          $22,310
..   ...                            ...                 ...               ...
51    AR                       OUACHITA               2,386          $17,989
52    AR                          PERRY                 962           $9,720
53    AR                       PHILLIPS               1,352          $11,669
54    AR                           PIKE                 924           $6,037
55    AR                       POINSETT               1,860          $11,742
56    AR                           POLK               1,927          $20,599
57    AR                           POPE               5,264          $36,541
58    AR                        PRAIRIE                 849           $7,311
59    AR                        PULASKI              32,005         $434,181
60    AR                       RANDOLPH               1,539          $16,128
61    AR                  SAINT FRANCIS               1,798          $13,398
62    AR                         SALINE              10,441          $73,628
63    AR                          SCOTT                 949           $7,611
64    AR                         SEARCY                 774           $8,286
65    AR                      SEBASTIAN              10,454          $76,221
66    AR                         SEVIER               1,089           $6,730
67    AR                          SHARP               2,038          $18,750
68    AR                          STONE               1,135          $11,748
69    AR                          UNION               3,368          $22,910
70    AR                      VAN BUREN               1,982          $16,944
71    AR                     WASHINGTON              13,436         $134,394
72    AR                          WHITE               6,637          $61,087
73    AR                       WOODRUFF                 611           $4,630
74    AR                           YELL               1,500          $13,980
75    AR              ARKANSAS (Totals)             249,274       $2,143,834
76    AR                CONG. DIST (01)              62,580         $505,480
77    AR                CONG. DIST (02)              63,942         $688,795
78    AR                CONG. DIST (03)              60,104         $445,524
79    AR                CONG. DIST (04)              62,649         $504,034
80    AR              ARKANSAS (Totals)             249,274       $2,143,834

[81 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     AZ                         APACHE               4,515          $27,572
1     AZ                        COCHISE              22,805         $180,559
2     AZ                       COCONINO               9,129          $47,123
3     AZ                           GILA               6,271          $34,247
4     AZ                         GRAHAM               2,923          $15,721
5     AZ                       GREENLEE               1,156           $4,226
6     AZ                         LA PAZ               2,850          $14,572
7     AZ                       MARICOPA             270,634       $1,787,224
8     AZ                         MOHAVE              26,134         $151,098
9     AZ                         NAVAJO               7,284          $47,003
10    AZ                           PIMA              89,600         $723,287
11    AZ                          PINAL              39,752         $171,697
12    AZ                     SANTA CRUZ               2,092          $13,328
13    AZ                        YAVAPAI              27,996         $298,973
14    AZ                           YUMA              19,065          $90,405
15    AZ               ARIZONA (Totals)             532,206       $3,607,036
16    AZ                CONG. DIST (01)              60,374         $316,340
17    AZ                CONG. DIST (02)              84,160         $644,326
18    AZ                CONG. DIST (03)              40,523         $356,491
19    AZ                CONG. DIST (04)              92,688         $618,404
20    AZ                CONG. DIST (05)              59,401         $275,440
21    AZ                CONG. DIST (06)              52,993         $287,855
22    AZ                CONG. DIST (07)              26,189         $328,521
23    AZ                CONG. DIST (08)              72,464         $349,867
24    AZ                CONG. DIST (09)              43,413         $429,793
25    AZ               ARIZONA (Totals)             532,206       $3,607,036
    State County/ Congressional District Veteran Population* Total Expenditure
0      CA                        ALAMEDA              59,133         $471,701
1      CA                         ALPINE                 127             $392
2      CA                         AMADOR               4,413          $19,946
3      CA                          BUTTE              18,055         $110,053
4      CA                      CALAVERAS               5,730          $34,321
5      CA                         COLUSA               1,226           $7,382
6      CA                   CONTRA COSTA              55,196         $350,727
7      CA                      DEL NORTE               2,597          $18,966
8      CA                      EL DORADO              15,822          $83,670
9      CA                         FRESNO              45,032         $380,526
10     CA                          GLENN               1,787           $9,692
11     CA                       HUMBOLDT              10,461          $95,981
12     CA                       IMPERIAL               7,670          $53,221
13     CA                           INYO               1,572           $9,251
14     CA                           KERN              47,962         $282,018
15     CA                          KINGS              12,613          $73,948
16     CA                           LAKE               6,752          $64,937
17     CA                         LASSEN               3,647          $17,347
18     CA                    LOS ANGELES             314,667       $2,538,479
19     CA                         MADERA               8,558          $61,774
20     CA                          MARIN              12,996          $68,468
21     CA                       MARIPOSA               2,179          $12,568
22     CA                      MENDOCINO               6,583          $62,840
23     CA                         MERCED              11,322          $82,221
24     CA                          MODOC                 977           $6,486
25     CA                           MONO               1,265           $2,882
26     CA                       MONTEREY              19,642         $183,037
27     CA                           NAPA               9,968          $53,334
28     CA                         NEVADA               9,395          $57,326
29     CA                         ORANGE             126,806         $711,610
..    ...                            ...                 ...               ...
83     CA                CONG. DIST (25)              32,550         $148,836
84     CA                CONG. DIST (26)              37,610         $219,232
85     CA                CONG. DIST (27)              26,132          $88,279
86     CA                CONG. DIST (28)              20,559         $135,571
87     CA                CONG. DIST (29)              14,200         $189,876
88     CA                CONG. DIST (30)              27,705         $155,208
89     CA                CONG. DIST (31)              34,056         $305,597
90     CA                CONG. DIST (32)              21,729         $121,266
91     CA                CONG. DIST (33)              32,571         $332,131
92     CA                CONG. DIST (34)              12,282         $147,302
93     CA                CONG. DIST (35)              22,486         $147,322
94     CA                CONG. DIST (36)              53,989         $388,938
95     CA                CONG. DIST (37)              21,945         $290,154
96     CA                CONG. DIST (38)              26,637         $157,589
97     CA                CONG. DIST (39)              27,256         $123,935
98     CA                CONG. DIST (40)               9,977          $92,142
99     CA                CONG. DIST (41)              32,385         $337,979
100    CA                CONG. DIST (42)              44,494         $310,358
101    CA                CONG. DIST (43)              25,676         $263,621
102    CA                CONG. DIST (44)              17,124         $165,818
103    CA                CONG. DIST (45)              32,127         $130,054
104    CA                CONG. DIST (46)              17,259         $144,092
105    CA                CONG. DIST (47)              32,534         $341,376
106    CA                CONG. DIST (48)              36,105         $203,639
107    CA                CONG. DIST (49)              48,373         $376,911
108    CA                CONG. DIST (50)              54,301         $496,903
109    CA                CONG. DIST (51)              34,530         $417,296
110    CA                CONG. DIST (52)              54,849         $502,878
111    CA                CONG. DIST (53)              61,150         $669,109
112    CA            CALIFORNIA (Totals)           1,851,470      $14,318,281

[113 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     CO                          ADAMS              30,759         $189,509
1     CO                        ALAMOSA               1,095           $8,522
2     CO                       ARAPAHOE              44,235         $266,783
3     CO                      ARCHULETA               1,031           $8,105
4     CO                           BACA                 390           $1,847
5     CO                           BENT                 549           $6,770
6     CO                        BOULDER              16,729          $65,784
7     CO                     BROOMFIELD               3,580          $19,381
8     CO                        CHAFFEE               1,932           $8,145
9     CO                       CHEYENNE                 148             $464

   State County/ Congressional District Veteran Population* Total Expenditure
0     MT                     BEAVERHEAD                 971           $5,930
1     MT                       BIG HORN                 882           $5,721
2     MT                         BLAINE                 579           $5,014
3     MT                     BROADWATER                 526           $6,594
4     MT                         CARBON                 868           $6,704
5     MT                         CARTER                  74             $574
6     MT                        CASCADE              11,138          $82,010
7     MT                       CHOUTEAU                 540           $4,145
8     MT                         CUSTER               1,255          $14,003
9     MT                        DANIELS                 195             $905
10    MT                         DAWSON                 886           $4,025
11    MT                     DEER LODGE               1,171           $8,102
12    MT                         FALLON                 198           $1,004
13    MT                         FERGUS               1,134           $9,619
14    MT                       FLATHEAD               9,238          $57,561
15    MT                       GALLATIN               6,517          $39,347
16    MT                       GARFIELD                 106             $376
17    MT                        GLACIER                 858           $6,846
18    MT                  GOLDEN VALLEY                  94             $804
19    MT                        GRANITE                 393           $2,553
20    MT                           HILL               1,338           $8,729
21    MT                      JEFFERSON               1,202          $14,669
22    MT                   JUDITH BASIN                 217           $1,572
23    MT                           LAKE               3,148          $15,781
24    MT                LEWIS AND CLARK               7,151          $97,023
25    MT                        LIBERTY                 129             $968
26    MT                        LINCOLN               2,675          $18,420
27    MT                         MCCONE                 155           $1,067
28    MT                        MADISON                 873           $5,450
29    MT                        MEAGHER                 234           $1,727
30    MT                        MINERAL                 558           $4,719
31    MT                       MISSOULA               9,928          $62,262
32    MT                    MUSSELSHELL                 528           $4,589
33    MT                           PARK               1,568           $8,081
34    MT                      PETROLEUM                  37             $434
35    MT                       PHILLIPS                 336           $2,362
36    MT                        PONDERA                 558           $3,895
37    MT                   POWDER RIVER                 126             $862
38    MT                         POWELL               1,050           $5,622
39    MT                        PRAIRIE                 130           $1,315
40    MT                        RAVALLI               5,037          $38,424
41    MT                       RICHLAND                 664           $3,701
42    MT                      ROOSEVELT                 865           $4,478
43    MT                        ROSEBUD                 773           $5,162
44    MT                        SANDERS               1,571          $12,300
45    MT                       SHERIDAN                 311             $939
46    MT                     SILVER BOW               3,442          $25,478
47    MT                     STILLWATER                 800           $6,319
48    MT                    SWEET GRASS                 359           $2,163
49    MT                          TETON                 648           $3,657
50    MT                          TOOLE                 523           $2,502
51    MT                       TREASURE                  83             $460
52    MT                         VALLEY                 729           $5,117
53    MT                      WHEATLAND                 187           $2,176
54    MT                         WIBAUX                  73             $442
55    MT                    YELLOWSTONE              14,018          $97,052
56    MT               MONTANA (Totals)              99,646         $731,755
57    MT                CONG. DIST (01)              99,646         $731,755
58    MT               MONTANA (Totals)              99,646         $731,755
    State County/ Congressional District Veteran Population* Total Expenditure
0      NC                       ALAMANCE              11,502          $71,432
1      NC                      ALEXANDER               2,805          $18,561
2      NC                      ALLEGHANY                 910           $5,421
3      NC                          ANSON               1,667          $10,076
4      NC                           ASHE               1,912          $13,956
5      NC                          AVERY               1,148           $8,926
6      NC                       BEAUFORT               3,890          $31,238
7      NC                         BERTIE               1,168           $8,725
8      NC                         BLADEN               3,016          $20,227
9      NC                      BRUNSWICK              13,450          $77,012
10     NC                       BUNCOMBE              19,908         $192,474
11     NC                          BURKE               7,041          $51,957
12     NC                       CABARRUS              13,288          $86,998
13     NC                       CALDWELL               6,213          $43,431
14     NC                         CAMDEN               1,064          $10,068
15     NC                       CARTERET               8,472          $64,569
16     NC                        CASWELL               2,005          $12,146
17     NC                        CATAWBA              11,853          $76,613
18     NC                        CHATHAM               6,210          $22,430
19     NC                       CHEROKEE               2,700          $23,400
20     NC                         CHOWAN               1,635           $7,550
21     NC                           CLAY               1,051           $8,726
22     NC                      CLEVELAND               7,450          $57,927
23     NC                       COLUMBUS               3,786          $35,751
24     NC                         CRAVEN              14,531         $112,766
25     NC                     CUMBERLAND              49,239         $693,950
26     NC                      CURRITUCK               3,128          $19,020
27     NC                           DARE               3,246          $12,128
28     NC                       DAVIDSON              13,887          $64,686
29     NC                          DAVIE               3,218          $18,989
..    ...                            ...                 ...               ...
85     NC                          SURRY               4,584          $37,459
86     NC                          SWAIN               1,244          $10,079
87     NC                   TRANSYLVANIA               3,482          $19,381
88     NC                        TYRRELL                 402           $1,124
89     NC                          UNION              13,302          $65,633
90     NC                          VANCE               2,475          $26,322
91     NC                           WAKE              59,109         $343,077
92     NC                         WARREN               1,556          $13,760
93     NC                     WASHINGTON                 926           $8,652
94     NC                        WATAUGA               2,555          $17,961
95     NC                          WAYNE              13,159         $107,504
96     NC                         WILKES               4,173          $29,947
97     NC                         WILSON               5,543          $46,203
98     NC                         YADKIN               2,513          $14,940
99     NC                         YANCEY               1,496          $14,685
100    NC        NORTH CAROLINA (Totals)             775,020       $5,949,873
101    NC                CONG. DIST (01)              51,025         $554,837
102    NC                CONG. DIST (02)              73,105         $623,461
103    NC                CONG. DIST (03)              85,608         $725,586
104    NC                CONG. DIST (04)              60,742         $647,851
105    NC                CONG. DIST (05)              55,059         $340,707
106    NC                CONG. DIST (06)              56,383         $305,589
107    NC                CONG. DIST (07)              65,665         $442,472
108    NC                CONG. DIST (08)              54,358         $381,863
109    NC                CONG. DIST (09)              49,226         $213,063
110    NC                CONG. DIST (10)              58,830         $441,788
111    NC                CONG. DIST (11)              64,692         $474,469
112    NC                CONG. DIST (12)              42,379         $467,635
113    NC                CONG. DIST (13)              57,947         $330,552
114    NC        NORTH CAROLINA (Totals)             775,020       $5,949,873

[115 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     ND                          ADAMS                 203           $1,139
1     ND                         BARNES                 945           $6,644
2     ND                         BENSON                 406           $2,837
3     ND                       BILLINGS                 104             $188
4     ND                      BOTTINEAU                 653           $3,025
5     ND                         BOWMAN                 239           $1,039
6     ND                          BURKE                 218             $868
7     ND                       BURLEIGH               7,231          $32,394
8     ND                           CASS              10,511         $111,195
9     ND                       CAVALIER                 352           $1,168
10    ND                         DICKEY                 497           $1,630
11    ND                         DIVIDE                 232             $646
12    ND                           DUNN                 338           $1,824
13    ND                           EDDY                 185           $1,167
14    ND                         EMMONS                 321           $1,926
15    ND                         FOSTER                 241           $1,007
16    ND                  GOLDEN VALLEY                 163             $416
17    ND                    GRAND FORKS               6,177          $36,091
18    ND                          GRANT                 236           $1,097
19    ND                         GRIGGS                 207           $2,847
20    ND                      HETTINGER                 280           $1,296
21    ND                         KIDDER                 202           $1,255
22    ND                       LA MOURE                 344           $1,771
23    ND                          LOGAN                 139           $1,066
24    ND                        MCHENRY                 583           $2,632
25    ND                       MCINTOSH                 231           $1,539
26    ND                       MCKENZIE                 507           $2,651
27    ND                         MCLEAN                 877           $4,917
28    ND                         MERCER                 705           $2,668
29    ND                         MORTON               2,249          $13,882
30    ND                      MOUNTRAIL                 571           $3,292
31    ND                         NELSON                 350           $2,914
32    ND                         OLIVER                 145             $643
33    ND                        PEMBINA                 714           $3,705
34    ND                         PIERCE                 390           $1,631
35    ND                         RAMSEY                 897           $5,234
36    ND                         RANSOM                 519           $4,318
37    ND                       RENVILLE                 327           $1,051
38    ND                       RICHLAND               1,124           $8,107
39    ND                        ROLETTE                 739           $4,655
40    ND                        SARGENT                 317           $2,155
41    ND                       SHERIDAN                 137             $412
42    ND                          SIOUX                 328           $2,022
43    ND                          SLOPE                  29             $179
44    ND                          STARK               2,103          $12,785
45    ND                         STEELE                 224           $1,351
46    ND                       STUTSMAN               1,804          $10,616
47    ND                         TOWNER                 226           $1,034
48    ND                         TRAILL                 763           $6,101
49    ND                          WALSH               1,024           $5,137
50    ND                           WARD               6,688          $35,102
51    ND                          WELLS                 363           $1,373
52    ND                       WILLIAMS               2,038          $10,361
53    ND          NORTH DAKOTA (Totals)              57,395         $367,003
54    ND                CONG. DIST (01)              57,395         $367,003
55    ND          NORTH DAKOTA (Totals)              57,395         $367,003
   State County/ Congressional District Veteran Population* Total Expenditure
0     NE                          ADAMS               2,331          $21,416
1     NE                       ANTELOPE                 603           $5,160
2     NE                         ARTHUR                  28              $70
3     NE                         BANNER                  47              $89
4     NE                         BLAINE                  26             $433
5     NE                          BOONE                 527           $4,264
6     NE                      BOX BUTTE                 996           $5,859
7     NE                           BOYD                 185           $1,620
8     NE                          BROWN                 247           $2,986
9     NE                        BUFFALO               2,904          $22,257
10    NE                           BURT                 684           $4,048
11    NE                         BUTLER                 691           $4,388
12    NE                           CASS               3,067          $22,299
13    NE                          CEDAR                 714           $4,408
14    NE                          CHASE                 278           $1,536
15    NE                         CHERRY                 467           $3,139
16    NE                       CHEYENNE                 773           $5,588
17    NE                           CLAY                 528           $4,039
18    NE                         COLFAX                 635           $1,934
19    NE                         CUMING                 684           $3,266
20    NE                         CUSTER                 870           $7,573
21    NE                         DAKOTA               1,248           $7,143
22    NE                          DAWES                 721           $7,324
23    NE                         DAWSON               1,552           $8,293
24    NE                          DEUEL                 219           $1,076
25    NE                          DIXON                 509           $2,282
26    NE                          DODGE               3,315          $21,345
27    NE                        DOUGLAS              37,766         $268,866
28    NE                          DUNDY                 167             $804
29    NE                       FILLMORE                 508           $5,357
..   ...                            ...                 ...               ...
68    NE                         PHELPS                 725           $5,148
69    NE                         PIERCE                 522           $2,553
70    NE                         PLATTE               2,133          $12,626
71    NE                           POLK                 432           $2,600
72    NE                     RED WILLOW                 857           $7,180
73    NE                     RICHARDSON                 823           $5,980
74    NE                           ROCK                 108             $874
75    NE                         SALINE               1,079           $7,222
76    NE                          SARPY              19,009         $174,613
77    NE                       SAUNDERS               1,774          $12,803
78    NE                   SCOTTS BLUFF               2,720          $22,093
79    NE                         SEWARD               1,063           $8,440
80    NE                       SHERIDAN                 505           $6,862
81    NE                        SHERMAN                 281           $3,307
82    NE                          SIOUX                  95             $336
83    NE                        STANTON                 458           $2,068
84    NE                         THAYER                 478           $3,131
85    NE                         THOMAS                  59             $780
86    NE                       THURSTON                 475           $1,619
87    NE                         VALLEY                 338           $3,559
88    NE                     WASHINGTON               1,403           $9,107
89    NE                          WAYNE                 669           $2,432
90    NE                        WEBSTER                 324           $2,761
91    NE                        WHEELER                  71             $622
92    NE                           YORK               1,064           $8,930
93    NE              NEBRASKA (Totals)             143,375       $1,136,146
94    NE                CONG. DIST (01)              50,801         $385,189
95    NE                CONG. DIST (02)              46,205         $372,778
96    NE                CONG. DIST (03)              46,369         $378,179
97    NE              NEBRASKA (Totals)             143,375       $1,136,146

[98 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     NH                        BELKNAP               6,192          $40,415
1     NH                        CARROLL               5,548          $27,177
2     NH                       CHESHIRE               7,196          $38,006
3     NH                           COOS               3,385          $23,235
4     NH                        GRAFTON               7,498          $52,423
5     NH                   HILLSBOROUGH              30,775         $199,525
6     NH                      MERRIMACK              13,378          $71,507
7     NH                     ROCKINGHAM              24,116         $128,791
8     NH                      STRAFFORD              11,290          $59,519
9     NH                       SULLIVAN               4,283          $33,455
10    NH         NEW HAMPSHIRE (Totals)             113,660         $674,052
11    NH                CONG. DIST (01)              56,969         $355,806
12    NH                CONG. DIST (02)              56,692         $318,246
13    NH         NEW HAMPSHIRE (Totals)             113,660         $674,052
   State County/ Congressional District Veteran Population* Total Expenditure
0     NJ                       ATLANTIC              17,514          $73,394

    State County/ Congressional District Veteran Population* Total Expenditure
0      CA                        ALAMEDA              56,608         $492,636
1      CA                         ALPINE                 129             $295
2      CA                         AMADOR               4,306          $24,409
3      CA                          BUTTE              17,696         $112,275
4      CA                      CALAVERAS               5,630          $33,264
5      CA                         COLUSA               1,205           $6,589
6      CA                   CONTRA COSTA              53,369         $386,501
7      CA                      DEL NORTE               2,563          $19,821
8      CA                      EL DORADO              15,508          $91,199
9      CA                         FRESNO              44,041         $416,375
10     CA                          GLENN               1,749           $9,955
11     CA                       HUMBOLDT              10,259          $96,473
12     CA                       IMPERIAL               7,641          $51,197
13     CA                           INYO               1,519          $10,221
14     CA                           KERN              47,178         $285,202
15     CA                          KINGS              12,795          $79,894
16     CA                           LAKE               6,602          $70,764
17     CA                         LASSEN               3,615          $19,910
18     CA                    LOS ANGELES             301,821       $2,644,554
19     CA                         MADERA               8,433          $69,540
20     CA                          MARIN              12,379          $74,488
21     CA                       MARIPOSA               2,143          $13,943
22     CA                      MENDOCINO               6,421          $66,969
23     CA                         MERCED              11,082          $83,600
24     CA                          MODOC                 960           $6,342
25     CA                           MONO               1,281           $3,191
26     CA                       MONTEREY              18,992         $188,944
27     CA                           NAPA               9,709          $60,532
28     CA                         NEVADA               9,146          $57,153
29     CA                         ORANGE             121,737         $719,228
..    ...                            ...                 ...               ...
83     CA                CONG. DIST (25)              31,206         $167,084
84     CA                CONG. DIST (26)              36,361         $226,655
85     CA                CONG. DIST (27)              25,164         $168,134
86     CA                CONG. DIST (28)              19,736         $194,629
87     CA                CONG. DIST (29)              13,603         $155,237
88     CA                CONG. DIST (30)              26,624         $180,759
89     CA                CONG. DIST (31)              33,614         $304,260
90     CA                CONG. DIST (32)              20,816         $126,980
91     CA                CONG. DIST (33)              31,344         $304,477
92     CA                CONG. DIST (34)              11,749         $184,057
93     CA                CONG. DIST (35)              22,070         $204,312
94     CA                CONG. DIST (36)              53,463         $460,289
95     CA                CONG. DIST (37)              21,082         $258,477
96     CA                CONG. DIST (38)              25,535         $189,099
97     CA                CONG. DIST (39)              26,244         $155,344
98     CA                CONG. DIST (40)               9,553         $123,444
99     CA                CONG. DIST (41)              31,956         $296,803
100    CA                CONG. DIST (42)              43,860         $369,028
101    CA                CONG. DIST (43)              24,629         $213,023
102    CA                CONG. DIST (44)              16,406         $171,651
103    CA                CONG. DIST (45)              30,829         $171,423
104    CA                CONG. DIST (46)              16,548         $133,635
105    CA                CONG. DIST (47)              31,198         $256,392
106    CA                CONG. DIST (48)              34,685         $189,250
107    CA                CONG. DIST (49)              47,545         $406,714
108    CA                CONG. DIST (50)              53,636         $460,711
109    CA                CONG. DIST (51)              34,243         $409,920
110    CA                CONG. DIST (52)              54,236         $629,404
111    CA                CONG. DIST (53)              60,568         $589,201
112    CA            CALIFORNIA (Totals)           1,802,446      $14,938,931

[113 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     CO                          ADAMS              30,534         $194,320
1     CO                        ALAMOSA               1,081           $8,660
2     CO                       ARAPAHOE              43,705         $287,641
3     CO                      ARCHULETA               1,019           $8,611
4     CO                           BACA                 374           $1,656
5     CO                           BENT                 542           $7,597
6     CO                        BOULDER              16,275          $70,673
7     CO                     BROOMFIELD               3,552          $22,440
8     CO                        CHAFFEE               1,903           $8,271
9     CO                       CHEYENNE                 145             $734
10    CO                    CLEAR CREEK                 843           $3,795
11    CO                        CONEJOS                 561           $5,105
12    CO                       COSTILLA                 306           $3,786
13    CO                        CROWLEY                 586           $4,172
14    CO                         CUSTER                 522           $4,840
15    CO                          DELTA               3,134          $27,131
16    CO                         DENVER              31,459         $740,107
17    CO                        DOLORES                 171           $1,277
18    CO                        DOUGLAS              21,251          $99,766
19    CO                          EAGLE               2,268           $5,706
20    CO                         ELBERT               2,264           $9,925
21    CO                        EL PASO              83,461         $849,901
22    CO                        FREMONT               7,153          $39,167
23    CO                       GARFIELD               3,729          $17,724
24    CO                         GILPIN                 411           $3,239
25    CO                          GRAND               1,022           $5,068
26    CO                       GUNNISON                 944           $4,383
27    CO                       HINSDALE                  67             $418
28    CO                       HUERFANO                 995           $7,831
29    CO                        JACKSON                 163             $628
..   ...                            ...                 ...               ...
43    CO                       MONTROSE               3,609          $27,677
44    CO                         MORGAN               1,738           $7,504
45    CO                          OTERO               1,674          $17,051
46    CO                          OURAY                 416           $2,052
47    CO                           PARK               1,784          $12,346
48    CO                       PHILLIPS                 318           $1,117
49    CO                         PITKIN                 897           $1,798
50    CO                        PROWERS                 811           $6,277
51    CO                         PUEBLO              16,663         $146,575
52    CO                     RIO BLANCO                 578           $3,296
53    CO                     RIO GRANDE               1,043           $8,031
54    CO                          ROUTT               1,293           $4,642
55    CO                       SAGUACHE                 485           $2,339
56    CO                       SAN JUAN                  65             $193
57    CO                     SAN MIGUEL                 378           $1,478
58    CO                       SEDGWICK                 259           $1,920
59    CO                         SUMMIT               1,389           $3,537
60    CO                         TELLER               3,170          $24,003
61    CO                     WASHINGTON                 421           $1,417
62    CO                           WELD              21,105         $106,957
63    CO                           YUMA                 692           $2,374
64    CO              COLORADO (Totals)             409,469       $3,482,533
65    CO                CONG. DIST (01)              39,914         $803,077
66    CO                CONG. DIST (02)              47,290         $264,178
67    CO                CONG. DIST (03)              62,407         $502,553
68    CO                CONG. DIST (04)              57,602         $294,418
69    CO                CONG. DIST (05)              96,741         $925,205
70    CO                CONG. DIST (06)              52,464         $322,841
71    CO                CONG. DIST (07)              53,051         $370,261
72    CO              COLORADO (Totals)             409,469       $3,482,533

[73 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     CT                      FAIRFIELD              37,668         $184,570
1     CT                       HARTFORD              52,078         $294,534
2     CT                     LITCHFIELD              14,202          $67,608
3     CT                      MIDDLESEX              11,540          $58,900
4     CT                      NEW HAVEN              46,041         $431,927
5     CT                     NEW LONDON              25,476         $120,127
6     CT                        TOLLAND               9,995          $44,413
7     CT                        WINDHAM               9,548          $47,043
8     CT           CONNECTICUT (Totals)             206,549       $1,249,124
9     CT                CONG. DIST (01)              41,839         $244,849
10    CT                CONG. DIST (02)              57,973         $268,051
11    CT                CONG. DIST (03)              38,789         $379,158
12    CT                CONG. DIST (04)              27,426         $138,998
13    CT                CONG. DIST (05)              40,522         $218,068
14    CT           CONNECTICUT (Totals)             206,549       $1,249,124
  State County/ Congressional District Veteran Population* Total Expenditure
0    DC           DISTRICT OF COLUMBIA              29,470       $2,960,157
1    DC                    DC (Totals)              29,470       $2,960,157
2    DC                CONG. DIST (01)              29,470       $2,960,157
3    DC                    DC (Totals)              29,470       $2,960,157
  State County/ Congressional District Veteran Population* Total Expenditure
0    DE                           KENT              19,806         $115,579
1    DE                     NEW CASTLE              34,992         $223,429
2    DE                         SUSSEX              22,556          $83,270
3    DE              DELAWARE (Totals)              77,354         $422,278
4    DE                CONG. DIST (01)              77,354         $422,278
5    DE              DELAWARE (Totals)              77,354         $422,278
   State County/ Congressional District Veteran Population* Total Expenditure
0     FL                        ALACHUA              18,515         $248,350
1     FL                          BAKER               2,786          $15,094
2     FL                            BAY              23,522         $153,718
3     FL                       BRADFORD               4,134          $24,647
4     FL                        BREVARD              65,915         $550,525
5     FL                        BROWARD              83,301         $629,104
6     FL                        CALHOUN               1,268           $8,387
7     FL                      CHARLOTTE              20,182         $126,446
8     FL                         CITRUS              28,095         $143,978
9     FL                           CLAY              30,788         $197,417
10    FL                        COLLIER              28,221          $99,704
11    FL                       COLUMBIA               8,196         $113,816
12    FL                        DE SOTO               2,411          $15,305
13    FL                          DIXIE               1,647          $20,767
14    FL                          DUVAL              98,830         $603,676
15    FL                       ESCAMBIA              41,641         $283,768
16    FL                        FLAGLER              12,610          $71,119
17    FL                       FRANKLIN               1,499           $6,860
18    FL                        GADSDEN               3,874          $26,360
19    FL                      GILCHRIST               1,647          $16,323
20    FL                         GLADES               1,043           $7,183
21    FL                           GULF               1,790           $9,550
22    FL                       HAMILTON               1,288          $12,060
23    FL                         HARDEE               1,548           $8,945
24    FL                         HENDRY               1,865          $14,240
25    FL                       HERNANDO              22,515         $178,957
26    FL                      HIGHLANDS              10,313          $75,311
27    FL                   HILLSBOROUGH              93,172       $1,070,288
28    FL                         HOLMES               2,068          $16,699
29    FL                   INDIAN RIVER              14,810          $87,121
..   ...                            ...                 ...               ...
66    FL                     WASHINGTON               2,683          $16,010
67    FL               FLORIDA (Totals)           1,558,441      $12,276,149
68    FL                CONG. DIST (01)             105,982         $749,027
69    FL                CONG. DIST (02)              67,944         $424,520
70    FL                CONG. DIST (03)              83,687         $737,757
71    FL                CONG. DIST (04)              84,693         $477,826
72    FL                CONG. DIST (05)              53,269         $489,688
73    FL                CONG. DIST (06)              81,399         $548,731
74    FL                CONG. DIST (07)              52,962         $415,957
75    FL                CONG. DIST (08)              82,115         $677,884
76    FL                CONG. DIST (09)              43,382         $437,116
77    FL                CONG. DIST (10)              60,338         $504,936
78    FL                CONG. DIST (11)             107,988         $676,308
79    FL                CONG. DIST (12)              72,365         $597,654
80    FL                CONG. DIST (13)              67,583         $709,830
81    FL                CONG. DIST (14)              47,511         $780,404
82    FL                CONG. DIST (15)              58,234         $489,644
83    FL                CONG. DIST (16)              69,778         $406,125
84    FL                CONG. DIST (17)              72,448         $489,246
85    FL                CONG. DIST (18)              56,506         $443,555
86    FL                CONG. DIST (19)              65,758         $340,788
87    FL                CONG. DIST (20)              28,058         $315,717
88    FL                CONG. DIST (21)              41,967         $263,492
89    FL                CONG. DIST (22)              43,738         $335,145
90    FL                CONG. DIST (23)              29,480         $238,971
91    FL                CONG. DIST (24)              18,511         $260,943
92    FL                CONG. DIST (25)              19,641         $134,749
93    FL                CONG. DIST (26)              24,928         $173,328
94    FL                CONG. DIST (27)              18,180         $156,809
95    FL               FLORIDA (Totals)           1,558,441      $12,276,149

[96 rows x 4 columns]
    State County/ Congressional District Veteran Population* Total Expenditure
0      GA                        APPLING               1,169           $6,577
1      GA                       ATKINSON                 421           $3,703
2      GA                          BACON                 802           $4,820
3      GA                          BAKER                 303           $1,373
4      GA                        BALDWIN               4,050          $24,251
5      GA                          BANKS               1,041           $7,275
6      GA                         BARROW               5,884          $27,822
7      GA                         BARTOW               7,859          $38,620
8      GA                       BEN HILL               1,215          $11,138
9      GA                        BERRIEN               1,492          $13,783
10     GA                           BIBB              11,712          $94,330
11     GA                       BLECKLEY               1,012           $9,971
12     GA                       BRANTLEY               1,277           $9,471
13     GA                         BROOKS               1,374          $10,128
14     GA                          BRYAN               3,995          $37,900
15     GA                        BULLOCH               5,043          $28,263
16     GA                          BURKE               1,791          $16,636
17     GA                          BUTTS               2,373          $14,148
18     GA                        CALHOUN                 443           $3,211
19     GA                         CAMDEN               7,368          $49,546
20     GA                        CANDLER                 764           $5,119
21     GA                        CARROLL               8,063          $60,500
22     GA                        CATOOSA               5,221          $23,651
23     GA                       CHARLTON                 943           $6,244
24     GA                        CHATHAM              27,480         $204,092
25     GA                  CHATTAHOOCHEE               1,394           $4,461
26     GA                      CHATTOOGA               1,954          $11,153
27     GA                       CHEROKEE              18,069          $82,397
28     GA                         CLARKE               5,872          $35,774
29     GA                           CLAY                 281           $1,637
..    ...                            ...                 ...               ...
145    GA                         WALKER               5,244          $33,848
146    GA                         WALTON               6,659          $48,133
147    GA                           WARE               3,154          $24,062
148    GA                         WARREN                 371           $3,512
149    GA                     WASHINGTON               1,436          $14,276
150    GA                          WAYNE               2,816          $17,028
151    GA                        WEBSTER                 189           $1,041
152    GA                        WHEELER                 513           $4,879
153    GA                          WHITE               2,408          $14,013
154    GA                      WHITFIELD               4,876          $29,204
155    GA                         WILCOX                 722           $5,334

Empty DataFrame
Columns: []
Index: [(Year, State, County/ Congressional District, Veteran Population*, Total Expenditure, Compensation & Pension, Construction, Education & Vocational Rehabilitation/ Employment, Loan Guaranty#, General Operating Expenses, Insurance & Indemnities, Medical Care), (15, MS, ADAMS, 2,118, $20,169 , $8,851 ,  $- , $522 ,  $- , $643 , $278 , $9,875 ), (15, MS, ALCORN, 2,224, $16,617 , $10,374 , $410 , $506 ,  $- , $263 , $238 , $4,826 ), (15, MS, AMITE, 1,089, $6,656 , $3,181 ,  $- , $213 ,  $- ,  $- , $27 , $3,235 ), (15, MS, ATTALA, 1,348, $13,237 , $6,114 ,  $- , $191 ,  $- ,  $- , $68 , $6,864 ), (15, MS, BENTON, 475, $2,835 , $1,212 ,  $- , $85 ,  $- ,  $- , $3 , $1,534 ), (15, MS, BOLIVAR, 2,051, $12,033 , $6,582 ,  $- , $636 ,  $- ,  $- , $125 , $4,690 ), (15, MS, CALHOUN, 924, $7,726 , $4,795 ,  $- , $274 ,  $- ,  $- , $23 , $2,635 ), (15, MS, CARROLL, 767, $3,819 , $1,917 ,  $- , $154 ,  $- ,  $- , $20 , $1,727 ), (15, MS, CHICKASAW, 1,002, $7,184 , $4,665 ,  $- , $183 ,  $- ,  $- , $104 , $2,233 ), (15, MS, CHOCTAW, 695, $4,274 , $1,744 ,  $- , $128 ,  $- ,  $- , $1 , $2,402 ), (15, MS, CLAIBORNE, 493, $3,856 , $1,666 ,  $- , $110 ,  $- ,  $- , $41 , $2,040 ), (15, MS, CLARKE, 1,366, $8,166 , $4,884 ,  $- , $332 ,  $- ,  $- , $162 , $2,787 ), (15, MS, CLAY, 1,360, $7,718 , $4,199 ,  $- , $418 ,  $- ,  $- , $56 , $3,045 ), (15, MS, COAHOMA, 1,400, $10,008 , $5,100 ,  $- , $441 ,  $- ,  $- , $41 , $4,426 ), (15, MS, COPIAH, 1,849, $18,712 , $8,121 ,  $- , $693 ,  $- ,  $- , $64 , $9,834 ), (15, MS, COVINGTON, 1,262, $12,554 , $7,032 ,  $- , $555 ,  $- ,  $- , $50 , $4,916 ), (15, MS, DE SOTO, 14,736, $72,849 , $35,966 ,  $- , $5,292 ,  $- ,  $- , $415 , $31,175 ), (15, MS, FORREST, 5,975, $59,379 , $33,686 ,  $- , $7,235 ,  $- ,  $- , $523 , $17,935 ), (15, MS, FRANKLIN, 584, $3,160 , $1,753 ,  $- , $100 ,  $- ,  $- , $32 , $1,275 ), (15, MS, GEORGE, 1,792, $9,761 , $5,451 ,  $- , $663 ,  $- ,  $- , $54 , $3,592 ), (15, MS, GREENE, 1,133, $4,363 , $2,227 ,  $- , $120 ,  $- ,  $- , $21 , $1,995 ), (15, MS, GRENADA, 1,502, $12,442 , $5,619 ,  $- , $610 ,  $- ,  $- , $30 , $6,183 ), (15, MS, HANCOCK, 4,467, $31,982 , $12,222 ,  $- , $1,433 ,  $- ,  $- , $310 , $18,017 ), (15, MS, HARRISON, 21,766, $282,596 , $105,833 , $33,557 , $20,432 ,  $- , $4,823 , $1,291 , $116,660 ), (15, MS, HINDS, 14,774, $208,497 , $63,022 , $636 , $8,590 ,  $- , $24,089 , $1,248 , $110,912 ), (15, MS, HOLMES, 941, $7,944 , $3,643 ,  $- , $393 ,  $- ,  $- , $35 , $3,873 ), (15, MS, HUMPHREYS, 427, $4,234 , $1,650 ,  $- , $64 ,  $- ,  $- , $11 , $2,509 ), (15, MS, ISSAQUENA, 117, $400 , $112 ,  $- , $5 ,  $- ,  $- ,  $- , $283 ), (15, MS, ITAWAMBA, 1,620, $7,863 , $4,931 ,  $- , $324 ,  $- ,  $- , $88 , $2,520 ), (15, MS, JACKSON, 14,999, $89,362 , $42,998 ,  $- , $7,055 ,  $- ,  $- , $592 , $38,717 ), (15, MS, JASPER, 1,124, $9,307 , $4,541 ,  $- , $370 ,  $- ,  $- , $11 , $4,386 ), (15, MS, JEFFERSON, 448, $3,075 , $1,638 ,  $- , $90 ,  $- ,  $- , $8 , $1,340 ), (15, MS, JEFFERSON DAVIS, 859, $7,039 , $2,693 ,  $- , $289 ,  $- ,  $- , $87 , $3,971 ), (15, MS, JONES, 4,044, $31,127 , $16,695 ,  $- , $1,157 ,  $- ,  $- , $334 , $12,942 ), (15, MS, KEMPER, 623, $3,687 , $1,940 ,  $- , $147 ,  $- ,  $- , $51 , $1,549 ), (15, MS, LAFAYETTE, 2,989, $14,572 , $6,916 ,  $- , $1,942 ,  $- ,  $- , $129 , $5,585 ), (15, MS, LAMAR, 4,015, $20,004 , $9,182 ,  $- , $1,060 ,  $- ,  $- , $71 , $9,691 ), (15, MS, LAUDERDALE, 6,426, $41,620 , $22,091 ,  $- , $2,780 ,  $- ,  $- , $494 , $16,255 ), (15, MS, LAWRENCE, 964, $10,664 , $5,120 ,  $- , $370 ,  $- ,  $- , $132 , $5,042 ), (15, MS, LEAKE, 1,045, $13,621 , $7,072 ,  $- , $491 ,  $- ,  $- , $44 , $6,014 ), (15, MS, LEE, 5,447, $28,679 , $17,373 ,  $- , $1,689 ,  $- ,  $- , $338 , $9,280 ), (15, MS, LEFLORE, 1,466, $12,218 , $5,404 ,  $- , $547 ,  $- ,  $- , $74 , $6,192 ), (15, MS, LINCOLN, 2,208, $17,346 , $7,238 ,  $- , $406 ,  $- ,  $- , $146 , $9,556 ), (15, MS, LOWNDES, 4,904, $42,530 , $24,792 ,  $- , $2,423 ,  $- ,  $- , $366 , $14,949 ), (15, MS, MADISON, 5,947, $46,962 , $21,701 ,  $- , $2,786 ,  $- ,  $- , $773 , $21,703 ), (15, MS, MARION, 1,698, $12,890 , $6,369 ,  $- , $371 ,  $- ,  $- , $53 , $6,097 ), (15, MS, MARSHALL, 2,327, $15,320 , $7,191 ,  $- , $547 ,  $- ,  $- , $252 , $7,331 ), (15, MS, MONROE, 2,764, $15,551 , $9,961 ,  $- , $616 ,  $- ,  $- , $134 , $4,840 ), (15, MS, MONTGOMERY, 799, $7,602 , $3,339 ,  $- , $219 ,  $- ,  $- , $34 , $4,010 ), (15, MS, NESHOBA, 1,820, $14,635 , $7,073 ,  $- , $741 ,  $- ,  $- , $15 , $6,807 ), (15, MS, NEWTON, 2,016, $11,268 , $6,015 ,  $- , $568 ,  $- ,  $- , $45 , $4,640 ), (15, MS, NOXUBEE, 506, $3,360 , $1,920 ,  $- , $98 ,  $- ,  $- , $39 , $1,303 ), (15, MS, OKTIBBEHA, 2,364, $14,183 , $6,560 ,  $- , $2,565 ,  $- ,  $- , $56 , $5,003 ), (15, MS, PANOLA, 1,875, $15,132 , $7,361 ,  $- , $611 ,  $- ,  $- , $167 , $6,993 ), (15, MS, PEARL RIVER, 5,232, $35,567 , $17,818 ,  $- , $1,581 ,  $- ,  $- , $128 , $16,040 ), (15, MS, PERRY, 1,075, $7,159 , $3,946 ,  $- , $243 ,  $- ,  $- , $190 , $2,779 ), (15, MS, PIKE, 2,806, $22,556 , $10,545 ,  $- , $751 ,  $- ,  $- , $71 , $11,188 ), (15, MS, PONTOTOC, 1,788, $9,609 , $5,402 ,  $- , $342 ,  $- ,  $- , $67 , $3,798 ), (15, MS, PRENTISS, 1,667, $7,322 , $4,277 ,  $- , $211 ,  $- ,  $- , $87 , $2,748 ), (15, MS, QUITMAN, 449, $3,636 , $2,195 ,  $- , $146 ,  $- ,  $- , $11 , $1,284 ), (15, MS, RANKIN, 11,691, $81,055 , $34,796 ,  $- , $4,812 ,  $- ,  $- , $771 , $40,676 ), (15, MS, SCOTT, 1,580, $13,266 , $5,964 ,  $- , $407 ,  $- ,  $- , $203 , $6,692 ), (15, MS, SHARKEY, 314, $2,067 , $848 ,  $- , $83 ,  $- ,  $- , $0 , $1,136 ), (15, MS, SIMPSON, 2,009, $16,876 , $7,745 ,  $- , $489 ,  $- ,  $- , $101 , $8,541 ), (15, MS, SMITH, 983, $5,946 , $3,170 ,  $- , $205 ,  $- ,  $- , $23 , $2,548 ), (15, MS, STONE, 1,628, $15,497 , $6,818 ,  $- , $986 ,  $- ,  $- , $90 , $7,603 ), (15, MS, SUNFLOWER, 1,656, $8,957 , $3,987 ,  $- , $448 ,  $- ,  $- , $115 , $4,406 ), (15, MS, TALLAHATCHIE, 796, $3,673 , $2,018 ,  $- , $236 ,  $- ,  $- , $23 , $1,396 ), (15, MS, TATE, 2,077, $12,240 , $6,086 ,  $- , $555 ,  $- ,  $- , $59 , $5,540 ), (15, MS, TIPPAH, 1,375, $7,135 , $4,824 ,  $- , $247 ,  $- ,  $- , $112 , $1,953 ), (15, MS, TISHOMINGO, 1,431, $7,779 , $5,160 ,  $- , $240 ,  $- ,  $- , $60 , $2,319 ), (15, MS, TUNICA, 474, $6,168 , $3,060 ,  $- , $258 ,  $- ,  $- , $37 , $2,814 ), (15, MS, UNION, 1,857, $8,628 , $5,151 ,  $- , $259 ,  $- ,  $- , $45 , $3,173 ), (15, MS, WALTHALL, 928, $7,235 , $3,281 ,  $- , $405 ,  $- ,  $- , $121 , $3,428 ), (15, MS, WARREN, 3,609, $22,974 , $10,557 ,  $- , $960 ,  $- ,  $- , $230 , $11,226 ), (15, MS, WASHINGTON, 2,931, $21,505 , $10,164 ,  $- , $782 ,  $- ,  $- , $246 , $10,313 ), (15, MS, WAYNE, 1,400, $7,644 , $4,060 ,  $- , $213 ,  $- ,  $- , $46 , $3,326 ), (15, MS, WEBSTER, 802, $5,585 , $3,290 ,  $- , $266 ,  $- ,  $- , $25 , $2,005 ), (15, MS, WILKINSON, 436, $2,759 , $1,572 ,  $- , $80 ,  $- ,  $- , $0 , $1,107 ), (15, MS, WINSTON, 1,394, $10,957 , $4,220 ,  $- , $226 ,  $- ,  $- , $134 , $6,377 ), (15, MS, YALOBUSHA, 950, $7,115 , $4,527 ,  $- , $288 ,  $- ,  $- , $67 , $2,232 ), (15, MS, YAZOO, 1,711, $15,366 , $6,502 ,  $- , $572 ,  $- ,  $- , $75 , $8,218 ), (15, MS, MISSISSIPPI (Totals), 218,980, $1,739,068 , $791,716 , $34,603 , $96,930 ,  $- , $29,819 , $12,941 , $773,059 ), (15, MS, CONG. DIST (01), 54,205, $314,797 , $173,142 , $410 , $16,913 ,  $- , $345 , $2,742 , $121,245 ), (15, MS, CONG. DIST (02), 42,960, $400,772 , $168,508 , $3 , $17,183 ,  $- , $554 , $2,853 , $211,671 ), (15, MS, CONG. DIST (03), 52,435, $414,339 , $181,451 , $633 , $20,172 ,  $- , $24,096 , $3,610 , $184,376 ), (15, MS, CONG. DIST (04), 69,379, $609,160 , $268,615 , $33,557 , $42,662 ,  $- , $4,823 , $3,736 , $255,767 ), (15, MS, MISSISSIPPI (Totals), 218,980, $1,739,068 , $791,716 , $34,603 , $96,930 ,  $- , $29,819 , $12,941 , $773,059 ), (=======, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan), (Year, State, County/ Congressional District, Veteran Population*, Total Expenditure, Compensation & Pension, Construction, Education & Vocational Rehabilitation/ Employment, Loan Guaranty#, General Operating Expenses, Insurance & Indemnities, Medical Care), (15, MS, ADAMS, 2,118, $20,169 , $8,851 ,  $- , $522 ,  $- , $643 , $278 , $9,875 ), (15, MS, ALCORN, 2,224, $16,617 , $10,374 , $410 , $506 ,  $- , $263 , $238 , $4,826 ), (15, MS, AMITE, 1,089, $6,656 , $3,181 ,  $- , $213 ,  $- ,  $- , $27 , $3,235 ), (15, MS, ATTALA, 1,348, $13,237 , $6,114 ,  $- , $191 ,  $- ,  $- , $68 , $6,864 ), (15, MS, BENTON, 475, $2,835 , $1,212 ,  $- , $85 ,  $- ,  $- , $3 , $1,534 ), (15, MS, BOLIVAR, 2,051, $12,033 , $6,582 ,  $- , $636 ,  $- ,  $- , $125 , $4,690 ), (15, MS, CALHOUN, 924, $7,726 , $4,795 ,  $- , $274 ,  $- ,  $- , $23 , $2,635 ), (15, MS, CARROLL, 767, $3,819 , $1,917 ,  $- , $154 ,  $- ,  $- , $20 , $1,727 ), (15, MS, CHICKASAW, 1,002, $7,184 , $4,665 ,  $- , $183 ,  $- ,  $- , $104 , $2,233 ), ...]

[180 rows x 0 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     MT                     BEAVERHEAD                 961           $5,831
1     MT                       BIG HORN                 879           $5,839
2     MT                         BLAINE                 579           $5,504
3     MT                     BROADWATER                 529          $10,431
4     MT                         CARBON                 853           $6,772
5     MT                         CARTER                  73             $754
6     MT                        CASCADE              11,166          $84,751
7     MT                       CHOUTEAU                 529           $3,478
8     MT                         CUSTER               1,241          $15,937
9     MT                        DANIELS                 189             $863
10    MT                         DAWSON                 879           $4,563
11    MT                     DEER LODGE               1,169           $9,576
12    MT                         FALLON                 196             $867
13    MT                         FERGUS               1,112          $10,337
14    MT                       FLATHEAD               9,180          $59,911
15    MT                       GALLATIN               6,517          $41,634
16    MT                       GARFIELD                 107             $480
17    MT                        GLACIER                 857           $7,236
18    MT                  GOLDEN VALLEY                  91             $938
19    MT                        GRANITE                 392           $2,781
20    MT                           HILL               1,328           $8,953
21    MT                      JEFFERSON               1,208          $15,338
22    MT                   JUDITH BASIN                 217           $1,640
23    MT                           LAKE               3,115          $18,504
24    MT                LEWIS AND CLARK               7,153         $110,463
25    MT                        LIBERTY                 128             $868
26    MT                        LINCOLN               2,664          $18,808
27    MT                         MCCONE                 153           $1,186
28    MT                        MADISON                 865           $5,782
29    MT                        MEAGHER                 230           $2,294
30    MT                        MINERAL                 553           $5,137
31    MT                       MISSOULA               9,836          $66,809
32    MT                    MUSSELSHELL                 520           $4,452
33    MT                           PARK               1,544           $9,266
34    MT                      PETROLEUM                  36             $414
35    MT                       PHILLIPS                 327           $2,415
36    MT                        PONDERA                 557           $3,803
37    MT                   POWDER RIVER                 122             $835
38    MT                         POWELL               1,058           $6,854
39    MT                        PRAIRIE                 127           $1,192
40    MT                        RAVALLI               5,004          $41,986
41    MT                       RICHLAND                 653           $3,736
42    MT                      ROOSEVELT                 864           $3,364
43    MT                        ROSEBUD                 768           $5,448
44    MT                        SANDERS               1,555          $13,263
45    MT                       SHERIDAN                 305             $939
46    MT                     SILVER BOW               3,438          $28,481
47    MT                     STILLWATER                 790           $6,923
48    MT                    SWEET GRASS                 350           $2,590
49    MT                          TETON                 645           $4,133
50    MT                          TOOLE                 522           $2,878
51    MT                       TREASURE                  80             $275
52    MT                         VALLEY                 714           $4,476
53    MT                      WHEATLAND                 182           $1,980
54    MT                         WIBAUX                  73             $364
55    MT                    YELLOWSTONE              13,849          $96,356
56    MT               MONTANA (Totals)              99,034         $780,685
57    MT                CONG. DIST (01)              99,034         $780,685
58    MT               MONTANA (Totals)              99,034         $780,685
    State County/ Congressional District Veteran Population* Total Expenditure
0      NC                       ALAMANCE              11,378          $78,643
1      NC                      ALEXANDER               2,779          $18,875
2      NC                      ALLEGHANY                 897           $6,190
3      NC                          ANSON               1,652          $11,224
4      NC                           ASHE               1,882          $13,140
5      NC                          AVERY               1,128           $9,141
6      NC                       BEAUFORT               3,827          $32,230
7      NC                         BERTIE               1,146           $8,891
8      NC                         BLADEN               3,031          $21,182
9      NC                      BRUNSWICK              13,612          $83,048
10     NC                       BUNCOMBE              19,638         $197,940
11     NC                          BURKE               6,985          $54,562
12     NC                       CABARRUS              13,285          $97,414
13     NC                       CALDWELL               6,140          $46,597
14     NC                         CAMDEN               1,083          $10,772
15     NC                       CARTERET               8,439          $67,169
16     NC                        CASWELL               1,979          $11,122
17     NC                        CATAWBA              11,725          $81,705
18     NC                        CHATHAM               6,204          $22,093
19     NC                       CHEROKEE               2,678          $23,808
20     NC                         CHOWAN               1,628           $7,296
21     NC                           CLAY               1,040           $9,469
22     NC                      CLEVELAND               7,374          $59,597
23     NC                       COLUMBUS               3,785          $36,378
24     NC                         CRAVEN              14,748         $120,339
25     NC                     CUMBERLAND              50,010         $747,930
26     NC                      CURRITUCK               3,163          $20,915
27     NC                           DARE               3,209          $12,599
28     NC                       DAVIDSON              13,794          $71,114
29     NC                          DAVIE               3,193          $20,773
..    ...                            ...                 ...               ...
85     NC                          SURRY               4,496          $38,325
86     NC                          SWAIN               1,245          $10,349
87     NC                   TRANSYLVANIA               3,419          $18,736
88     NC                        TYRRELL                 401           $1,013
89     NC                          UNION              13,404          $71,577
90     NC                          VANCE               2,438          $28,850
91     NC                           WAKE              59,237         $362,903
92     NC                         WARREN               1,545          $14,830
93     NC                     WASHINGTON                 913           $7,422
94     NC                        WATAUGA               2,494          $18,084
95     NC                          WAYNE              13,286         $114,185
96     NC                         WILKES               4,126          $32,501
97     NC                         WILSON               5,492          $50,488
98     NC                         YADKIN               2,493          $14,761
99     NC                         YANCEY               1,469          $14,909
100    NC        NORTH CAROLINA (Totals)             773,884       $6,380,720
101    NC                CONG. DIST (01)              50,907         $580,578
102    NC                CONG. DIST (02)              73,579         $739,174
103    NC                CONG. DIST (03)              86,894         $765,315
104    NC                CONG. DIST (04)              61,107         $624,218
105    NC                CONG. DIST (05)              54,525         $382,521
106    NC                CONG. DIST (06)              55,711         $343,034
107    NC                CONG. DIST (07)              65,927         $503,252
108    NC                CONG. DIST (08)              54,154         $416,562
109    NC                CONG. DIST (09)              49,070         $271,921
110    NC                CONG. DIST (10)              58,201         $454,834
111    NC                CONG. DIST (11)              63,973         $508,954
112    NC                CONG. DIST (12)              41,792         $440,505
113    NC                CONG. DIST (13)              58,045         $349,851
114    NC        NORTH CAROLINA (Totals)             773,884       $6,380,720

[115 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     ND                          ADAMS                 198           $1,396
1     ND                         BARNES                 927           $6,795
2     ND                         BENSON                 400           $2,597
3     ND                       BILLINGS                 104             $427
4     ND                      BOTTINEAU                 647           $3,187
5     ND                         BOWMAN                 236           $1,213
6     ND                          BURKE                 212             $802
7     ND                       BURLEIGH               7,199          $35,761
8     ND                           CASS              10,462         $114,855
9     ND                       CAVALIER                 346           $1,644
10    ND                         DICKEY                 496           $1,668
11    ND                         DIVIDE                 228             $815
12    ND                           DUNN                 337           $2,587
13    ND                           EDDY                 179           $1,245
14    ND                         EMMONS                 312           $1,888
15    ND                         FOSTER                 233           $1,194
16    ND                  GOLDEN VALLEY                 157             $537

[76 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     AR                       ARKANSAS               1,290          $11,436
1     AR                         ASHLEY               1,524          $13,524
2     AR                         BAXTER               5,129          $37,486
3     AR                         BENTON              16,857         $120,619
4     AR                          BOONE               3,264          $26,502
5     AR                        BRADLEY                 784           $6,324
6     AR                        CALHOUN                 350           $2,511
7     AR                        CARROLL               2,342          $19,138
8     AR                         CHICOT                 718           $9,255
9     AR                          CLARK               1,455          $13,634
10    AR                           CLAY               1,153          $12,680
11    AR                       CLEBURNE               2,760          $27,220
12    AR                      CLEVELAND                 641           $6,667
13    AR                       COLUMBIA               1,654          $12,412
14    AR                         CONWAY               1,612          $19,609
15    AR                      CRAIGHEAD               6,083          $43,613
16    AR                       CRAWFORD               4,839          $47,170
17    AR                     CRITTENDEN               3,114          $29,078
18    AR                          CROSS               1,156           $8,984
19    AR                         DALLAS                 551           $5,204
20    AR                          DESHA                 766           $9,284
21    AR                           DREW               1,211          $10,249
22    AR                       FAULKNER               8,939          $85,178
23    AR                       FRANKLIN               1,440          $13,856
24    AR                         FULTON               1,183          $11,811
25    AR                        GARLAND              10,242          $84,322
26    AR                          GRANT               1,355          $14,238
27    AR                         GREENE               2,956          $29,432
28    AR                      HEMPSTEAD               1,362           $9,984
29    AR                     HOT SPRING               2,748          $23,851
..   ...                            ...                 ...               ...
51    AR                       OUACHITA               1,903          $18,828
52    AR                          PERRY                 885           $9,597
53    AR                       PHILLIPS               1,131          $11,033
54    AR                           PIKE                 822           $7,041
55    AR                       POINSETT               1,426          $12,040
56    AR                           POLK               1,957          $20,755
57    AR                           POPE               4,719          $38,972
58    AR                        PRAIRIE                 634           $7,620
59    AR                        PULASKI              30,934         $459,598
60    AR                       RANDOLPH               1,322          $15,036
61    AR                  SAINT FRANCIS               1,290          $13,935
62    AR                         SALINE              10,062          $79,216
63    AR                          SCOTT                 827           $9,100
64    AR                         SEARCY                 691           $7,956
65    AR                      SEBASTIAN               9,377          $77,945
66    AR                         SEVIER                 886           $6,955
67    AR                          SHARP               1,857          $19,194
68    AR                          STONE               1,184          $11,438
69    AR                          UNION               2,945          $20,919
70    AR                      VAN BUREN               1,742          $17,898
71    AR                     WASHINGTON              12,499         $131,713
72    AR                          WHITE               5,223          $60,414
73    AR                       WOODRUFF                 504           $4,445
74    AR                           YELL               1,471          $13,733
75    AR              ARKANSAS (Totals)             225,118       $2,215,940
76    AR                CONG. DIST (01)              55,459         $516,822
77    AR                CONG. DIST (02)              59,398         $734,336
78    AR                CONG. DIST (03)              53,212         $459,581
79    AR                CONG. DIST (04)              57,048         $505,201
80    AR              ARKANSAS (Totals)             225,118       $2,215,940

[81 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     AZ                         APACHE               2,829          $29,985
1     AZ                        COCHISE              19,799         $180,489
2     AZ                       COCONINO               8,528          $49,195
3     AZ                           GILA               5,915          $40,034
4     AZ                         GRAHAM               2,059          $14,516
5     AZ                       GREENLEE                 627           $4,234
6     AZ                         LA PAZ               2,364          $16,081
7     AZ                       MARICOPA             269,692       $1,970,194
8     AZ                         MOHAVE              24,899         $170,205
9     AZ                         NAVAJO               7,205          $50,122
10    AZ                           PIMA              90,420         $769,425
11    AZ                          PINAL              35,212         $207,128
12    AZ                     SANTA CRUZ               1,917          $14,406
13    AZ                        YAVAPAI              27,254         $309,254
14    AZ                           YUMA              16,331          $94,480
15    AZ               ARIZONA (Totals)             515,050       $3,919,749
16    AZ                CONG. DIST (01)              55,150         $372,111
17    AZ                CONG. DIST (02)              80,766         $661,273
18    AZ                CONG. DIST (03)              40,128         $387,063
19    AZ                CONG. DIST (04)              86,728         $655,007
20    AZ                CONG. DIST (05)              57,640         $336,934
21    AZ                CONG. DIST (06)              51,421         $370,288
22    AZ                CONG. DIST (07)              25,694         $317,381
23    AZ                CONG. DIST (08)              73,717         $369,529
24    AZ                CONG. DIST (09)              43,806         $450,162
25    AZ               ARIZONA (Totals)             515,050       $3,919,749
    State County/ Congressional District Veteran Population* Total Expenditure
0      CA                        ALAMEDA              53,920         $495,133
1      CA                         ALPINE                  98             $330
2      CA                         AMADOR               3,919          $25,461
3      CA                          BUTTE              16,375         $117,995
4      CA                      CALAVERAS               4,398          $34,263
5      CA                         COLUSA                 891           $7,014
6      CA                   CONTRA COSTA              51,832         $385,131
7      CA                      DEL NORTE               2,183          $20,084
8      CA                      EL DORADO              14,726          $92,302
9      CA                         FRESNO              40,870         $437,083
10     CA                          GLENN               1,401           $9,240
11     CA                       HUMBOLDT               8,907         $106,502
12     CA                       IMPERIAL               6,297          $52,094
13     CA                           INYO               1,432          $12,464
14     CA                           KERN              40,308         $308,174
15     CA                          KINGS               9,596          $86,452
16     CA                           LAKE               5,630          $74,079
17     CA                         LASSEN               2,245          $21,287
18     CA                    LOS ANGELES             294,652       $2,728,740
19     CA                         MADERA               7,684          $73,353
20     CA                          MARIN              11,869          $76,499
21     CA                       MARIPOSA               1,727          $13,389
22     CA                      MENDOCINO               5,899          $65,147
23     CA                         MERCED              11,259          $88,711
24     CA                          MODOC                 798           $6,787
25     CA                           MONO                 827           $3,958
26     CA                       MONTEREY              18,881         $199,459
27     CA                           NAPA               8,935          $60,214
28     CA                         NEVADA               8,632          $58,747
29     CA                         ORANGE             115,115         $758,169
..    ...                            ...                 ...               ...
83     CA                CONG. DIST (25)              32,294         $172,198
84     CA                CONG. DIST (26)              35,909         $238,039
85     CA                CONG. DIST (27)              22,949         $174,293
86     CA                CONG. DIST (28)              19,895         $201,525
87     CA                CONG. DIST (29)              15,170         $158,143
88     CA                CONG. DIST (30)              25,524         $187,918
89     CA                CONG. DIST (31)              30,719         $325,342
90     CA                CONG. DIST (32)              22,179         $130,238
91     CA                CONG. DIST (33)              29,087         $322,952
92     CA                CONG. DIST (34)              11,481         $174,542
93     CA                CONG. DIST (35)              20,714         $221,158
94     CA                CONG. DIST (36)              49,805         $497,245
95     CA                CONG. DIST (37)              19,114         $259,965
96     CA                CONG. DIST (38)              24,634         $165,098
97     CA                CONG. DIST (39)              26,403         $198,508
98     CA                CONG. DIST (40)               8,936         $118,529
99     CA                CONG. DIST (41)              30,343         $319,066
100    CA                CONG. DIST (42)              44,322         $404,146
101    CA                CONG. DIST (43)              23,437         $221,768
102    CA                CONG. DIST (44)              15,526         $179,959
103    CA                CONG. DIST (45)              29,644         $180,984
104    CA                CONG. DIST (46)              15,576         $140,144
105    CA                CONG. DIST (47)              29,287         $271,630
106    CA                CONG. DIST (48)              32,316         $199,950
107    CA                CONG. DIST (49)              49,429         $430,145
108    CA                CONG. DIST (50)              57,554         $486,116
109    CA                CONG. DIST (51)              35,972         $435,970
110    CA                CONG. DIST (52)              57,291         $655,080
111    CA                CONG. DIST (53)              66,865         $609,945
112    CA            CALIFORNIA (Totals)           1,735,213      $15,568,595

[113 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     CO                          ADAMS              29,055         $188,220
1     CO                        ALAMOSA                 990           $9,388
2     CO                       ARAPAHOE              44,661         $313,098
3     CO                      ARCHULETA               1,167           $9,118
4     CO                           BACA                 285           $1,632
5     CO                           BENT                 435           $6,921
6     CO                        BOULDER              14,788          $72,265
7     CO                     BROOMFIELD               4,089          $24,210
8     CO                        CHAFFEE               1,761           $8,845
9     CO                       CHEYENNE                 128             $933
10    CO                    CLEAR CREEK                 856           $4,611
11    CO                        CONEJOS                 544           $5,988
12    CO                       COSTILLA                 382           $3,949
13    CO                        CROWLEY                 294           $3,799
14    CO                         CUSTER                 542           $5,145
15    CO                          DELTA               3,032          $26,990
16    CO                         DENVER              32,925         $724,762
17    CO                        DOLORES                 154           $1,478
18    CO                        DOUGLAS              19,871         $106,331
19    CO                          EAGLE               1,575           $5,892
20    CO                         ELBERT               2,338          $10,053
21    CO                        EL PASO              98,711         $949,943
22    CO                        FREMONT               5,344          $41,504
23    CO                       GARFIELD               2,939          $18,424
24    CO                         GILPIN                 476           $3,355
25    CO                          GRAND                 795           $5,337
26    CO                       GUNNISON                 826           $4,320
27    CO                       HINSDALE                 115             $354
28    CO                       HUERFANO                 739           $8,537
29    CO                        JACKSON                 117             $642
..   ...                            ...                 ...               ...
43    CO                       MONTROSE               3,513          $29,841
44    CO                         MORGAN               1,558           $8,157
45    CO                          OTERO               1,489          $16,562
46    CO                          OURAY                 402           $1,703
47    CO                           PARK               1,678          $14,291
48    CO                       PHILLIPS                 334             $983
49    CO                         PITKIN                 671           $1,805
50    CO                        PROWERS                 713           $5,836
51    CO                         PUEBLO              14,777         $158,059
52    CO                     RIO BLANCO                 473           $3,144
53    CO                     RIO GRANDE                 857           $8,144
54    CO                          ROUTT               1,245           $4,581
55    CO                       SAGUACHE                 409           $2,980
56    CO                       SAN JUAN                  48             $158
57    CO                     SAN MIGUEL                 388           $1,393
58    CO                       SEDGWICK                 217           $1,568
59    CO                         SUMMIT               1,185           $3,959
60    CO                         TELLER               3,113          $25,564
61    CO                     WASHINGTON                 430           $1,827
62    CO                           WELD              16,902         $115,097
63    CO                           YUMA                 628           $2,046
64    CO              COLORADO (Totals)             407,616       $3,638,790
65    CO                CONG. DIST (01)              41,305         $787,133
66    CO                CONG. DIST (02)              47,136         $278,363
67    CO                CONG. DIST (03)              55,442         $523,761
68    CO                CONG. DIST (04)              50,558         $308,424
69    CO                CONG. DIST (05)             109,839       $1,029,240
70    CO                CONG. DIST (06)              52,687         $345,379
71    CO                CONG. DIST (07)              50,649         $366,490
72    CO              COLORADO (Totals)             407,616       $3,638,790

[73 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     CT                      FAIRFIELD              33,866         $179,024
1     CT                       HARTFORD              46,876         $294,150
2     CT                     LITCHFIELD              11,951          $66,535
3     CT                      MIDDLESEX              11,019          $59,717
4     CT                      NEW HAVEN              44,480         $432,499
5     CT                     NEW LONDON              24,714         $126,922
6     CT                        TOLLAND               9,898          $44,591
7     CT                        WINDHAM               8,803          $45,516
8     CT           CONNECTICUT (Totals)             191,607       $1,248,955
9     CT                CONG. DIST (01)              37,526         $247,582
10    CT                CONG. DIST (02)              55,736         $272,818
11    CT                CONG. DIST (03)              36,920         $369,317
12    CT                CONG. DIST (04)              24,733         $137,144
13    CT                CONG. DIST (05)              36,693         $222,094
14    CT           CONNECTICUT (Totals)             191,607       $1,248,955
  State County/ Congressional District Veteran Population* Total Expenditure
0    DC           DISTRICT OF COLUMBIA              28,413       $2,663,847
1    DC                    DC (Totals)              28,413       $2,663,847
2    DC                CONG. DIST (01)              28,413       $2,663,847
3    DC                    DC (Totals)              28,413       $2,663,847
  State County/ Congressional District Veteran Population* Total Expenditure
0    DE                           KENT              19,370         $126,414
1    DE                     NEW CASTLE              32,448         $225,761
2    DE                         SUSSEX              21,013          $89,303
3    DE              DELAWARE (Totals)              72,831         $441,478
4    DE                CONG. DIST (01)              72,831         $441,478
5    DE              DELAWARE (Totals)              72,831         $441,478
   State County/ Congressional District Veteran Population* Total Expenditure
0     FL                        ALACHUA              16,513         $240,914
1     FL                          BAKER               2,094          $14,275
2     FL                            BAY              24,571         $166,244
3     FL                       BRADFORD               2,337          $25,802
4     FL                        BREVARD              70,275         $597,526
5     FL                        BROWARD              85,475         $637,935
6     FL                        CALHOUN               1,348           $8,974
7     FL                      CHARLOTTE              22,916         $132,112
8     FL                         CITRUS              20,569         $152,903
9     FL                           CLAY              27,337         $212,547
10    FL                        COLLIER              29,324          $99,911
11    FL                       COLUMBIA               6,749         $115,057
12    FL                        DE SOTO               2,171          $14,596
13    FL                          DIXIE               1,659          $20,202
14    FL                          DUVAL              91,296         $630,106

55    ND          NORTH DAKOTA (Totals)              52,043         $375,097
   State County/ Congressional District Veteran Population* Total Expenditure
0     NE                          ADAMS               2,247          $23,028
1     NE                       ANTELOPE                 538           $4,538
2     NE                         ARTHUR                  35              $72
3     NE                         BANNER                  42             $192
4     NE                         BLAINE                  32             $308
5     NE                          BOONE                 420           $3,915
6     NE                      BOX BUTTE                 867           $6,165
7     NE                           BOYD                 197           $1,543
8     NE                          BROWN                 248           $2,681
9     NE                        BUFFALO               2,645          $23,390
10    NE                           BURT                 537           $3,806
11    NE                         BUTLER                 602           $4,938
12    NE                           CASS               2,826          $23,311
13    NE                          CEDAR                 645           $3,753
14    NE                          CHASE                 286           $1,252
15    NE                         CHERRY                 497           $3,275
16    NE                       CHEYENNE                 718           $5,989
17    NE                           CLAY                 496           $4,514
18    NE                         COLFAX                 502           $2,369
19    NE                         CUMING                 621           $3,850
20    NE                         CUSTER                 746           $7,311
21    NE                         DAKOTA               1,104           $7,659
22    NE                          DAWES                 692           $7,383
23    NE                         DAWSON               1,087           $8,428
24    NE                          DEUEL                 192             $935
25    NE                          DIXON                 425           $2,296
26    NE                          DODGE               2,944          $20,884
27    NE                        DOUGLAS              33,438         $264,652
28    NE                          DUNDY                 175             $827
29    NE                       FILLMORE                 464           $5,100
..   ...                            ...                 ...               ...
68    NE                         PHELPS                 595           $5,682
69    NE                         PIERCE                 569           $2,415
70    NE                         PLATTE               2,033          $12,710
71    NE                           POLK                 374           $2,762
72    NE                     RED WILLOW                 851           $7,447
73    NE                     RICHARDSON                 726           $5,391
74    NE                           ROCK                 120           $1,130
75    NE                         SALINE                 830           $6,286
76    NE                          SARPY              18,791         $181,883
77    NE                       SAUNDERS               1,668          $12,957
78    NE                   SCOTTS BLUFF               2,575          $22,406
79    NE                         SEWARD               1,064           $8,470
80    NE                       SHERIDAN                 431           $5,149
81    NE                        SHERMAN                 274           $2,962
82    NE                          SIOUX                 112             $358
83    NE                        STANTON                 380           $2,303
84    NE                         THAYER                 455           $2,883
85    NE                         THOMAS                  56             $407
86    NE                       THURSTON                 363           $2,239
87    NE                         VALLEY                 371           $3,145
88    NE                     WASHINGTON               1,509          $10,113
89    NE                          WAYNE                 602           $3,484
90    NE                        WEBSTER                 306           $2,910
91    NE                        WHEELER                  74             $412
92    NE                           YORK                 858           $9,806
93    NE              NEBRASKA (Totals)             133,003       $1,157,483
94    NE                CONG. DIST (01)              47,783         $389,873
95    NE                CONG. DIST (02)              41,524         $394,571
96    NE                CONG. DIST (03)              43,696         $373,039
97    NE              NEBRASKA (Totals)             133,003       $1,157,483

[98 rows x 4 columns]
   State County/ Congressional District Veteran Population* Total Expenditure
0     NH                        BELKNAP               5,678          $42,649
1     NH                        CARROLL               4,729          $28,310
2     NH                       CHESHIRE               6,460          $42,470
3     NH                           COOS               3,365          $25,484
4     NH                        GRAFTON               7,276          $58,421
5     NH                   HILLSBOROUGH              29,963         $212,862
6     NH                      MERRIMACK              12,818          $78,662
7     NH                     ROCKINGHAM              23,281         $139,050
8     NH                      STRAFFORD              10,650          $64,964
9     NH                       SULLIVAN               3,898          $39,542
10    NH         NEW HAMPSHIRE (Totals)             108,119         $732,415
11    NH                CONG. DIST (01)              53,108         $364,405
12    NH                CONG. DIST (02)              55,010         $368,010
13    NH         NEW HAMPSHIRE (Totals)             108,119         $732,415
   State County/ Congressional District Veteran Population* Total Expenditure
0     NJ                       ATLANTIC              15,558          $80,877
1     NJ                         BERGEN              29,500         $156,308
2     NJ                     BURLINGTON              32,631         $229,798
3     NJ                         CAMDEN              27,505         $169,382
4     NJ                       CAPE MAY               8,195          $37,820
5     NJ                     CUMBERLAND               7,624          $39,897
6     NJ                          ESSEX              23,251         $247,340
7     NJ                     GLOUCESTER              16,835          $99,257
8     NJ                         HUDSON              14,567          $92,555
9     NJ                      HUNTERDON               6,052          $31,458
10    NJ                         MERCER              13,576          $70,783
11    NJ                      MIDDLESEX              27,266         $142,966
12    NJ                       MONMOUTH              27,102         $147,566
13    NJ                         MORRIS              20,206          $83,367
14    NJ                          OCEAN              41,058         $215,352
15    NJ                        PASSAIC              14,904          $82,408
16    NJ                          SALEM               4,371          $24,534
17    NJ                       SOMERSET              10,684          $97,126
18    NJ                         SUSSEX               8,199          $43,606
19    NJ                          UNION              16,253         $116,032
20    NJ                         WARREN               6,182          $32,069
21    NJ            NEW JERSEY (Totals)             371,518       $2,240,502
22    NJ                CONG. DIST (01)              40,076         $252,670
23    NJ                CONG. DIST (02)              45,577         $239,348
24    NJ                CONG. DIST (03)              55,017         $332,569
25    NJ                CONG. DIST (04)              36,009         $184,725
26    NJ                CONG. DIST (05)              30,222         $146,426
27    NJ                CONG. DIST (06)              24,378         $143,434
28    NJ                CONG. DIST (07)              28,263         $177,274
29    NJ                CONG. DIST (08)              13,668         $120,106
30    NJ                CONG. DIST (09)              19,063         $123,048
31    NJ                CONG. DIST (10)              22,624         $243,751
32    NJ                CONG. DIST (11)              30,536         $129,012
33    NJ                CONG. DIST (12)              26,086         $148,140
34    NJ            NEW JERSEY (Totals)             371,518       $2,240,502
   State County/ Congressional District Veteran Population* Total Expenditure
0     NM                     BERNALILLO              53,591         $629,969
1     NM                         CATRON                 339           $4,779
2     NM                         CHAVES               5,098          $31,476
3     NM                         CIBOLA               1,756          $22,033
4     NM                         COLFAX               1,363          $11,678
5     NM                          CURRY               5,169          $41,898
6     NM                        DE BACA                 192           $1,619
7     NM                       DONA ANA              14,459         $119,582
8     NM                           EDDY               3,904          $24,166
9     NM                          GRANT               3,189          $22,730
10    NM                      GUADALUPE                 305           $4,535
11    NM                        HARDING                 113             $988
12    NM                        HIDALGO                 311           $1,875
13    NM                            LEA               3,461          $18,767
14    NM                        LINCOLN               2,172          $14,782
15    NM                     LOS ALAMOS               1,353           $4,178
16    NM                           LUNA               2,079          $15,103
17    NM                      MC KINLEY               3,171          $37,878
18    NM                           MORA                 334           $6,397
19    NM                          OTERO               8,680          $63,103
20    NM                           QUAY                 857           $9,188
21    NM                     RIO ARRIBA               2,217          $22,254
22    NM                      ROOSEVELT               1,174           $8,473
23    NM                       SANDOVAL              12,433         $128,264
24    NM                       SAN JUAN               7,831          $52,661
25    NM                     SAN MIGUEL               2,111          $26,384
26    NM                       SANTA FE              10,105          $89,087
27    NM                         SIERRA               1,919          $20,374
28    NM                        SOCORRO               1,119          $12,954
29    NM                           TAOS               2,571          $27,737
30    NM                       TORRANCE               1,261          $16,720
31    NM                          UNION                 327           $3,168
32    NM                       VALENCIA               6,346          $76,680
33    NM            NEW MEXICO (Totals)             161,311       $1,571,479
34    NM                CONG. DIST (01)              55,609         $658,030
35    NM                CONG. DIST (02)              55,678         $455,048
36    NM                CONG. DIST (03)              50,024         $458,401
37    NM            NEW MEXICO (Totals)             161,311       $1,571,479
   State County/ Congressional District Veteran Population* Total Expenditure
0     NV                      CHURCHILL               3,523          $35,497
1     NV                          CLARK             151,579       $1,320,334
2     NV                        DOUGLAS               4,916          $33,597
3     NV                           ELKO               3,187          $19,598
4     NV                      ESMERALDA                  97             $933
5     NV                         EUREKA                 273             $747
6     NV                       HUMBOLDT               1,215           $8,451
7     NV                         LANDER                 427           $1,927
8     NV                        LINCOLN                 419           $2,483
9     NV                           LYON               6,445          $64,926
10    NV                        MINERAL                 600           $4,658
11    NV                            NYE               6,261          $67,594
12    NV                       PERSHING                 486           $3,875
13    NV                         STOREY                 465           $3,741
14    NV                         WASHOE              36,096         $360,618
15    NV                     WHITE PINE                 783           $5,805
16    NV                    CARSON CITY               5,223          $44,331
17    NV                NEVADA (Totals)             221,996       $1,979,113
18    NV                CONG. DIST (01)              42,843         $423,607
19    NV                CONG. DIST (02)              61,086         $566,921
20    NV                CONG. DIST (03)              56,408         $460,868
21    NV                CONG. DIST (04)              61,659         $527,717
22    NV                NEVADA (Totals)             221,996       $1,979,113
   State County/ Congressional District Veteran Population* Total Expenditure
0     NY                         ALBANY              16,543         $130,441
1     NY                       ALLEGANY               4,017          $34,998
2     NY                          BRONX              30,554         $400,743
3     NY                         BROOME              13,495          $61,349
4     NY                    CATTARAUGUS               6,811          $52,692
5     NY                         CAYUGA               5,719          $37,879
6     NY                     CHAUTAUQUA              10,305          $80,187
7     NY                        CHEMUNG               7,307          $54,234
8     NY                       CHENANGO               4,060          $23,677
9     NY                        CLINTON               7,445          $40,385
10    NY                       COLUMBIA               4,106          $21,780
11    NY                       CORTLAND               3,043          $22,341
12    NY                       DELAWARE               3,407          $17,370
13    NY                       DUTCHESS              14,951         $127,645
14    NY                           ERIE              58,517         $550,435
15    NY                          ESSEX               3,365          $17,433
16    NY                       FRANKLIN               3,654          $22,145
17    NY                         FULTON               4,029          $21,127
18    NY                        GENESEE               4,430          $55,022
19    NY                         GREENE               3,702          $24,828
20    NY                       HAMILTON                 576           $1,489
21    NY                       HERKIMER               5,264          $25,008
22    NY                      JEFFERSON              14,805         $124,394
23    NY                          KINGS              44,347         $484,521
24    NY                          LEWIS               2,331          $16,323
25    NY                     LIVINGSTON               3,657          $24,832
26    NY                        MADISON               5,087          $32,121
27    NY                         MONROE              39,801         $216,374
28    NY                     MONTGOMERY               3,512          $21,568
29    NY                         NASSAU              48,869         $268,999
..   ...                            ...                 ...               ...
61    NY                          YATES               1,835          $15,383
62    NY              NEW YORK (Totals)             806,827       $6,311,502
63    NY                CONG. DIST (01)              35,781         $249,527
64    NY                CONG. DIST (02)              30,720         $218,065
65    NY                CONG. DIST (03)              28,132         $207,202
66    NY                CONG. DIST (04)              25,094         $145,282
67    NY                CONG. DIST (05)              18,775         $170,656
68    NY                CONG. DIST (06)              14,242         $106,613
69    NY                CONG. DIST (07)               9,547         $109,038
70    NY                CONG. DIST (08)              16,710         $174,216
71    NY                CONG. DIST (09)              12,729         $136,119
72    NY                CONG. DIST (10)              13,043         $141,441
73    NY                CONG. DIST (11)              23,171         $182,821
74    NY                CONG. DIST (12)              17,255         $192,574
75    NY                CONG. DIST (13)              14,032         $188,879
76    NY                CONG. DIST (14)              13,956         $120,648
77    NY                CONG. DIST (15)              11,374         $189,821
78    NY                CONG. DIST (16)              21,764         $173,734
79    NY                CONG. DIST (17)              22,257         $201,727
80    NY                CONG. DIST (18)              36,753         $282,580
81    NY                CONG. DIST (19)              45,714         $272,332
82    NY                CONG. DIST (20)              44,569         $289,561
83    NY                CONG. DIST (21)              64,555         $391,780
84    NY                CONG. DIST (22)              51,579         $303,271
85    NY                CONG. DIST (23)              54,782         $422,623
86    NY                CONG. DIST (24)              47,869         $368,686
87    NY                CONG. DIST (25)              38,157         $207,719
88    NY                CONG. DIST (26)              45,265         $470,771
89    NY                CONG. DIST (27)              48,999         $393,817
90    NY              NEW YORK (Totals)             806,827       $6,311,502

[91 rows x 4 columns]
    State County/ Congressional District Veteran Population* Total Expenditure
0      OH                          ADAMS               1,886          $18,060
1      OH                          ALLEN               7,218          $41,135
2      OH                        ASHLAND               4,036          $26,853
3      OH                      ASHTABULA               8,437          $57,195
4      OH                         ATHENS               3,357          $34,756
5      OH                       AUGLAIZE               3,255          $14,248
6      OH                        BELMONT               5,377          $28,885
7      OH                          BROWN               3,500          $24,765
8      OH                         BUTLER              23,946         $142,502
9      OH                        CARROLL               2,418          $12,229
10     OH                      CHAMPAIGN               3,141          $15,794
11     OH                          CLARK              13,514          $77,629
12     OH                       CLERMONT              14,833          $89,348
13     OH                        CLINTON               3,245          $24,998
14     OH                     COLUMBIANA               8,957          $55,241
15     OH                      COSHOCTON               2,759          $16,068
16     OH                       CRAWFORD               3,607          $20,326
17     OH                       CUYAHOGA              72,820       $3,463,304

In [25]:
fy15_mn.iloc[:,0]

Year                                              State  County/ Congressional District  Veteran Population*  Total Expenditure  Compensation & Pension  Construction  Education & Vocational Rehabilitation/ Employment  Loan Guaranty#  General Operating Expenses  Insurance & Indemnities  Medical Care    Unique Patients**
15                                                MN     AITKIN                          1,700                $18,211            $7,921                   $-           $204                                                $-              $-                         $335                     $9,751                        983
                                                         ANOKA                           22,975               $150,558           $65,859                  $-           $10,308                                             $-              $-                         $1,285                   $73,106                     7,280
                                                         BECKER                          2,919                $23,148            $10,223                  $-           $496                                                $-              $-                         $175                     $12,254                     1,179
                                                         BELTRAMI                        3,183                $30,677            $15,249                  $-           $1,159                                              $-              $-                         $381                     $13,887                     1,344
                                                         BENTON                          3,345                $30,014            $10,259                  $-           $627                                                $-              $-                         $107                     $19,020                     1,506
                                                         BIG STONE                       458                  $3,785             $2,003                   $-           $87                                                 $-              $-                         $14                      $1,682                        258
                                                         BLUE EARTH                      4,556                $27,062            $12,903                  $-           $2,564                                              $-              $-                         $412                     $11,183                     1,295
                                                         BROWN                           1,798                $14,140            $7,988                   $-           $474                                                $-              $-                         $172                     $5,506                        840
                                                         CARLTON                         3,326                $23,162            $14,309                  $-           $1,161                                              $-              $-                         $137                     $7,556                      1,007
                                                         CARVER                          4,910                $21,950            $10,251                  $-           $1,783                                              $-              $-                         $458                     $9,457                      1,134
                                                         CASS                            3,311                $29,986            $13,912                  $-           $304                                                $-              $-                         $232                     $15,538                     1,598
                                                         CHIPPEWA                        825                  $7,219             $2,927                   $-           $91                                                 $-              $-                         $46                      $4,156                        489
                                                         CHISAGO                         4,285                $29,515            $15,041                  $-           $1,975                                              $-              $-                         $538                     $11,960                     1,138
                                                         CLAY                            4,266                $34,413            $13,806                  $-           $1,740                                              $-              $-                         $512                     $18,356                     1,674
                                                         CLEARWATER                      784                  $8,144             $3,552                   $-           $131                                                $-              $-                         $14                      $4,448                        417
                                                         COOK                            501                  $3,226             $1,798                   $-           $26                                                 $-              $-                         $138                     $1,265                        120
                                                         COTTONWOOD                      796                  $5,840             $2,782                   $-           $90                                                 $-              $-                         $99                      $2,869                        349
                                                         CROW WING                       5,739                $54,738            $28,601                  $-           $1,487                                              $-              $-                         $484                     $24,166                     2,893
                                                         DAKOTA                          27,048               $183,497           $80,617                  $-           $13,655                                             $-              $-                         $2,279                   $86,945                     7,286
                                                         DODGE                           1,209                $6,572             $3,334                   $-           $330                                                $-              $-                         $24                      $2,884                        376
                                                         DOUGLAS                         3,196                $25,818            $13,323                  $-           $708                                                $-              $-                         $301                     $11,484                     1,523
                                                         FARIBAULT                       1,256                $7,566             $3,735                   $-           $319                                                $-              $-                         $69                      $3,444                        400
                                                         FILLMORE                        1,516                $8,325             $4,981                   $-           $393                                                $-              $-                         $76                      $2,875                        468
                                                         FREEBORN                        2,536                $17,708            $7,738                   $-           $278                                                $-              $-                         $243                     $9,449                      1,084
                                                         GOODHUE                         3,916                $21,223            $9,869                   $-           $1,241                                              $-              $-                         $378                     $9,735                      1,015
                                                         GRANT                           470                  $4,655             $2,249                   $-           $46                                                 $-              $-                         $26                      $2,333                        229
                                                         HENNEPIN                        59,728               $498,498           $149,388                $198          $36,517                                             $-             $85,117                     $9,962                   $217,317                   15,722
                                                         HOUSTON                         1,543                $8,733             $4,919                   $-           $387                                                $-              $-                         $221                     $3,206                        632
                                                         HUBBARD                         2,274                $17,882            $8,668                   $-           $315                                                $-              $-                         $241                     $8,659                        920
                                                                                                                                                                                                                                                                                                                     ...
                                                         ST. LOUIS                       18,471               $108,681           $56,921                  $-           $6,929                                              $-              $-                         $1,750                   $43,081                     5,695
                                                         SCOTT                           7,286                $54,161            $21,910                  $-           $8,165                                              $-              $-                         $682                     $23,404                     2,164
                                                         SHERBURNE                       6,363                $57,612            $26,577                  $-           $2,958                                              $-              $-                         $593                     $27,484                     2,543
                                                         SIBLEY                          1,160                $6,504             $3,082                   $-           $143                                                $-              $-                         $34                      $3,244                        386
                                                         STEARNS                         10,160               $159,966           $51,232                 $10,528       $3,923                                              $-             $1,371                      $686                     $92,227                     5,850
                                                         STEELE                          2,759                $13,016            $6,785                   $-           $745                                                $-              $-                         $104                     $5,382                        707
                                                         STEVENS                         511                  $3,018             $1,621                   $-           $146                                                $-              $-                         $23                      $1,229                        225
                                                         SWIFT                           925                  $6,989             $3,110                   $-           $211                                                $-              $-                         $38                      $3,629                        344
                                                         TODD                            2,078                $17,685            $6,677                   $-           $215                                                $-              $-                         $85                      $10,708                     1,070
                                                         TRAVERSE                        340                  $2,393             $1,236                   $-           $21                                                 $-              $-                         $5                       $1,131                        121
                                                         WABASHA                         1,775                $13,734            $7,047                   $-           $352                                                $-              $-                         $156                     $6,179                        678
                                                         WADENA                          1,183                $15,736            $9,366                   $-           $314                                                $-              $-                         $106                     $5,950                        629
                                                         WASECA                          1,696                $8,166             $3,908                   $-           $399                                                $-              $-                         $82                      $3,777                        476
                                                         WASHINGTON                      16,692               $91,299            $43,215                  $-           $8,157                                              $-              $-                         $1,424                   $38,504                     3,512
                                                         WATONWAN                        892                  $6,109             $2,913                   $-           $98                                                 $-              $-                         $76                      $3,022                        365
                                                         WILKIN                          462                  $3,435             $1,240                   $-           $89                                                 $-              $-                         $56                      $2,049                        178
                                                         WINONA                          3,495                $16,658            $7,922                   $-           $1,170                                              $-              $-                         $166                     $7,401                        968
                                                         WRIGHT                          9,081                $54,162            $24,451                  $-           $3,334                                              $-              $-                         $740                     $25,637                     2,570
                                                         YELLOW MEDICINE                 770                  $6,511             $3,261                   $-           $172                                                $-              $-                         $35                      $3,043                        360
                                                         MINNESOTA (Totals)              361,129              $2,637,124         $1,123,595              $10,726       $146,597                                            $-             $86,488                     $35,200                  $1,234,518                117,414
                                                         CONG. DIST (01)                 48,561               $264,401           $131,806                 $-           $14,163                                             $-              $-                         $3,647                   $114,785                   14,593
                                                         CONG. DIST (02)                 44,747               $295,300           $129,323                 $-           $24,785                                             $-              $-                         $3,790                   $137,402                   12,109
                                                         CONG. DIST (03)                 38,282               $207,705           $85,962                  $-           $19,424                                             $-              $-                         $4,990                   $97,330                     9,723
                                                         CONG. DIST (04)                 37,215               $230,471           $97,538                  $-           $19,322                                             $-              $-                         $4,480                   $109,132                    8,809
                                                         CONG. DIST (05)                 33,125               $359,952           $94,449                 $198          $22,046                                             $-             $85,117                     $5,745                   $152,397                    9,316
                                                         CONG. DIST (06)                 46,308               $401,664           $156,924                $10,528       $18,674                                             $-             $1,371                      $3,270                   $210,898                   17,223
                                                         CONG. DIST (07)                 51,105               $395,207           $182,457                 $-           $10,948                                             $-              $-                         $3,698                   $198,105                   21,911
                                                         CONG. DIST (08)                 61,786               $482,423           $245,138                 $-           $17,236                                             $-              $-                         $5,579                   $214,470                   23,730
                                                         MINNESOTA (Totals)              361,129              $2,637,124         $1,123,595              $10,726       $146,597                                            $-             $86,488                     $35,200                  $1,234,518                117,414
>>>>>>> 2e92f51f2b503d3f36fe8c62eb8fcba3f59fb38b  NaN    NaN                             NaN                  NaN                NaN                     NaN           NaN                                                NaN             NaN                         NaN                      NaN                           NaN
Name: <<<<<<< HEAD, Length: 198, dtype: object

In [213]:
# If you need to index by the "total" column
FY_14_LIST[3]["Veteran Population*"].describe()

count          26
unique         25
top       532,206
freq            2
Name: Veteran Population*, dtype: object

In [218]:
def cleanString(fydata14,fydata15,fydata16,columnIndex=4):

    for i in range(len(fydata14)): #len = 53 with FY_14_LIST
        fydata14[i].iloc[:,columnIndex] = fydata14[i].iloc[:,columnIndex].str.replace("$","")
        fydata15[i].iloc[:,columnIndex] = fydata15[i].iloc[:,columnIndex].str.replace("$","")
        fydata16[i].iloc[:,columnIndex] = fydata16[i].iloc[:,columnIndex].str.replace("$","")
        
        #replace commas
        fydata14[i].iloc[:,columnIndex] = fydata14[i].iloc[:,columnIndex].str.replace(",","")
        fydata15[i].iloc[:,columnIndex] = fydata15[i].iloc[:,columnIndex].str.replace(",","")
        fydata16[i].iloc[:,columnIndex] = fydata16[i].iloc[:,columnIndex].str.replace(",","")
        
        #convert to float
        fydata14[i].iloc[:,columnIndex] = fydata14[i].iloc[:,columnIndex].astype(float)
        fydata15[i].iloc[:,columnIndex] = fydata15[i].iloc[:,columnIndex].astype(float)
        fydata16[i].iloc[:,columnIndex] = fydata16[i].iloc[:,columnIndex].astype(float)
        
        return [fydata14, fydata15, fydata16]

In [234]:
#cleanDF = cleanString(FY_14_LIST,FY_15_LIST, FY_16_LIST)

In [237]:
listLength = len(FY_16_LIST)
listLength

53

In [221]:
# get fy summary stats for mean, median over 3 years
def get_stats(fydata14,fydata15,fydata16, columnCode):
    new_df[columnCode] = fydata14[1][columnCode].copy() # just copying dataframe
    for i in range(len(fydata14)): #len = 53 with FY_14_LIST
        new_df[columnCode] += (float(fy15data[i]) + fy16data[i])
    
            
    return new_df