In [22]:
'''
import numpy as np
import pandas as pd
import matplotlib.pylab as plt 
%matplotlib inline

fy14_ak = pd.read_csv('fy14_ak.csv')
fy14_al = pd.read_csv('fy14_al.csv')
fy14_ar = pd.read_csv('fy14_ar.csv')
fy14_az = pd.read_csv('fy14_az.csv')
fy14_ca = pd.read_csv('fy14_ca.csv')
fy14_co = pd.read_csv('fy14_co.csv')
fy14_ct = pd.read_csv('fy14_ct.csv')
fy14_dc = pd.read_csv('fy14_dc.csv')
fy14_de = pd.read_csv('fy14_de.csv')
fy14_fl = pd.read_csv('fy14_fl.csv')
fy14_ga = pd.read_csv('fy14_ga.csv')
fy14_gu = pd.read_csv('fy14_gu.csv')
fy14_hi = pd.read_csv('fy14_hi.csv')
fy14_ia = pd.read_csv('fy14_ia.csv')
fy14_id = pd.read_csv('fy14_id.csv')
fy14_il = pd.read_csv('fy14_il.csv')
fy14_in = pd.read_csv('fy14_in.csv')
fy14_ks = pd.read_csv('fy14_ks.csv')
fy14_ky = pd.read_csv('fy14_ky.csv')
fy14_la = pd.read_csv('fy14_la.csv')
fy14_ma = pd.read_csv('fy14_ma.csv')
fy14_md = pd.read_csv('fy14_md.csv')
fy14_me = pd.read_csv('fy14_me.csv')
fy14_mi = pd.read_csv('fy14_mi.csv')
fy14_mn = pd.read_csv('fy14_mn.csv')
fy14_mo = pd.read_csv('fy14_mo.csv')
fy14_ms = pd.read_csv('fy14_ms.csv')
fy14_mt = pd.read_csv('fy14_mt.csv')
fy14_nc = pd.read_csv('fy14_nc.csv')
fy14_nd = pd.read_csv('fy14_nd.csv')
fy14_ne = pd.read_csv('fy14_ne.csv')
fy14_nh = pd.read_csv('fy14_nh.csv')
fy14_nj = pd.read_csv('fy14_nj.csv')
fy14_nm = pd.read_csv('fy14_nm.csv')
fy14_nv = pd.read_csv('fy14_nv.csv')
fy14_ny = pd.read_csv('fy14_ny.csv')
fy14_oh = pd.read_csv('fy14_oh.csv')
fy14_ok = pd.read_csv('fy14_ok.csv')
fy14_or = pd.read_csv('fy14_or.csv')
fy14_pa = pd.read_csv('fy14_pa.csv')
fy14_pr = pd.read_csv('fy14_pr.csv')
fy14_ri = pd.read_csv('fy14_ri.csv')
fy14_sc = pd.read_csv('fy14_sc.csv')
fy14_sd = pd.read_csv('fy14_sd.csv')
fy14_tn = pd.read_csv('fy14_tn.csv')
fy14_tx = pd.read_csv('fy14_tx.csv')
fy14_ut = pd.read_csv('fy14_ut.csv')
fy14_va = pd.read_csv('fy14_va.csv')
fy14_vt = pd.read_csv('fy14_vt.csv')
fy14_wa = pd.read_csv('fy14_wa.csv')
fy14_wi = pd.read_csv('fy14_wi.csv')
fy14_wv = pd.read_csv('fy14_wv.csv')
fy14_wy = pd.read_csv('fy14_wy.csv')

#fy15
fy15_ak = pd.read_csv('fy15_ak.csv')
fy15_al = pd.read_csv('fy15_al.csv')
fy15_ar = pd.read_csv('fy15_ar.csv')
fy15_az = pd.read_csv('fy15_az.csv')
fy15_ca = pd.read_csv('fy15_ca.csv')
fy15_co = pd.read_csv('fy15_co.csv')
fy15_ct = pd.read_csv('fy15_ct.csv')
fy15_dc = pd.read_csv('fy15_dc.csv')
fy15_de = pd.read_csv('fy15_de.csv')
fy15_fl = pd.read_csv('fy15_fl.csv')
fy15_ga = pd.read_csv('fy15_ga.csv')
fy15_gu = pd.read_csv('fy15_gu.csv')
fy15_hi = pd.read_csv('fy15_hi.csv')
fy15_ia = pd.read_csv('fy15_ia.csv')
fy15_id = pd.read_csv('fy15_id.csv')
fy15_il = pd.read_csv('fy15_il.csv')
fy15_in = pd.read_csv('fy15_in.csv')
fy15_ks = pd.read_csv('fy15_ks.csv')
fy15_ky = pd.read_csv('fy15_ky.csv')
fy15_la = pd.read_csv('fy15_la.csv')
fy15_ma = pd.read_csv('fy15_ma.csv')
fy15_md = pd.read_csv('fy15_md.csv')
fy15_me = pd.read_csv('fy15_me.csv')
fy15_mi = pd.read_csv('fy15_mi.csv')
fy15_mn = pd.read_csv('fy15_mn.csv')
fy15_mo = pd.read_csv('fy15_mo.csv')
fy15_ms = pd.read_csv('fy15_ms.csv')
fy15_mt = pd.read_csv('fy15_mt.csv')
fy15_nc = pd.read_csv('fy15_nc.csv')
fy15_nd = pd.read_csv('fy15_nd.csv')
fy15_ne = pd.read_csv('fy15_ne.csv')
fy15_nh = pd.read_csv('fy15_nh.csv')
fy15_nj = pd.read_csv('fy15_nj.csv')
fy15_nm = pd.read_csv('fy15_nm.csv')
fy15_nv = pd.read_csv('fy15_nv.csv')
fy15_ny = pd.read_csv('fy15_ny.csv')
fy15_oh = pd.read_csv('fy15_oh.csv')
fy15_ok = pd.read_csv('fy15_ok.csv')
fy15_or = pd.read_csv('fy15_or.csv')
fy15_pa = pd.read_csv('fy15_pa.csv')
fy15_pr = pd.read_csv('fy15_pr.csv')
fy15_ri = pd.read_csv('fy15_ri.csv')
fy15_sc = pd.read_csv('fy15_sc.csv')
fy15_sd = pd.read_csv('fy15_sd.csv')
fy15_tn = pd.read_csv('fy15_tn.csv')
fy15_tx = pd.read_csv('fy15_tx.csv')
fy15_ut = pd.read_csv('fy15_ut.csv')
fy15_va = pd.read_csv('fy15_va.csv')
fy15_vt = pd.read_csv('fy15_vt.csv')
fy15_wa = pd.read_csv('fy15_wa.csv')
fy15_wi = pd.read_csv('fy15_wi.csv')
fy15_wv = pd.read_csv('fy15_wv.csv')
fy15_wy = pd.read_csv('fy15_wy.csv')

#fy16
fy16_ak = pd.read_csv('fy16_ak.csv')
fy16_al = pd.read_csv('fy16_al.csv')
fy16_ar = pd.read_csv('fy16_ar.csv')
fy16_az = pd.read_csv('fy16_az.csv')
fy16_ca = pd.read_csv('fy16_ca.csv')
fy16_co = pd.read_csv('fy16_co.csv')
fy16_ct = pd.read_csv('fy16_ct.csv')
fy16_dc = pd.read_csv('fy16_dc.csv')
fy16_de = pd.read_csv('fy16_de.csv')
fy16_fl = pd.read_csv('fy16_fl.csv')
fy16_ga = pd.read_csv('fy16_ga.csv')
fy16_gu = pd.read_csv('fy16_gu.csv')
fy16_hi = pd.read_csv('fy16_hi.csv')
fy16_ia = pd.read_csv('fy16_ia.csv')
fy16_id = pd.read_csv('fy16_id.csv')
fy16_il = pd.read_csv('fy16_il.csv')
fy16_in = pd.read_csv('fy16_in.csv')
fy16_ks = pd.read_csv('fy16_ks.csv')
fy16_ky = pd.read_csv('fy16_ky.csv')
fy16_la = pd.read_csv('fy16_la.csv')
fy16_ma = pd.read_csv('fy16_ma.csv')
fy16_md = pd.read_csv('fy16_md.csv')
fy16_me = pd.read_csv('fy16_me.csv')
fy16_mi = pd.read_csv('fy16_mi.csv')
fy16_mn = pd.read_csv('fy16_mn.csv')
fy16_mo = pd.read_csv('fy16_mo.csv')
fy16_ms = pd.read_csv('fy16_ms.csv')
fy16_mt = pd.read_csv('fy16_mt.csv')
fy16_nc = pd.read_csv('fy16_nc.csv')
fy16_nd = pd.read_csv('fy16_nd.csv')
fy16_ne = pd.read_csv('fy16_ne.csv')
fy16_nh = pd.read_csv('fy16_nh.csv')
fy16_nj = pd.read_csv('fy16_nj.csv')
fy16_nm = pd.read_csv('fy16_nm.csv')
fy16_nv = pd.read_csv('fy16_nv.csv')
fy16_ny = pd.read_csv('fy16_ny.csv')
fy16_oh = pd.read_csv('fy16_oh.csv')
fy16_ok = pd.read_csv('fy16_ok.csv')
fy16_or = pd.read_csv('fy16_or.csv')
fy16_pa = pd.read_csv('fy16_pa.csv')
fy16_pr = pd.read_csv('fy16_pr.csv')
fy16_ri = pd.read_csv('fy16_ri.csv')
fy16_sc = pd.read_csv('fy16_sc.csv')
fy16_sd = pd.read_csv('fy16_sd.csv')
fy16_tn = pd.read_csv('fy16_tn.csv')
fy16_tx = pd.read_csv('fy16_tx.csv')
fy16_ut = pd.read_csv('fy16_ut.csv')
fy16_va = pd.read_csv('fy16_va.csv')
fy16_vt = pd.read_csv('fy16_vt.csv')
fy16_wa = pd.read_csv('fy16_wa.csv')
fy16_wi = pd.read_csv('fy16_wi.csv')
fy16_wv = pd.read_csv('fy16_wv.csv')
fy16_wy = pd.read_csv('fy16_wy.csv')

STATE_NAMES=['Alaska','Alabama','Arkansas','Arizona','California','Colorado','Connecticut','DC','Delaware','Florida',
            'Georgia','Guam','Hawaii','Iowa','Idaho','Illinois','Indiana','Kansas','Kentucky','Louisiana','Massachusetts',
            'Maryland', 'Maine','Michigan','Missouri','Mississippi','Montana','North Carolina','North Dakota','Nebraska',
            'New Hampshire','New Jersey','New Mexico','Nevada','New York','Ohio','Oklahoma','Oregon','Pennsylvania',
            'Puerto Rico','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Virginia','Vermont',
            'Washington','Wisconsin','West Virginia','Wyoming']

FY_14_LIST=[
    fy14_ak,fy14_al,fy14_ar,fy14_az,fy14_ca,fy14_co,fy14_ct,fy14_dc,fy14_de,fy14_fl,fy14_ga,fy14_gu,fy14_hi,fy14_ia,
    fy14_id,fy14_il,fy14_in,fy14_ks,fy14_ky,fy14_la,fy14_ma,fy14_md,fy14_me,fy14_mi,fy14_mn,fy14_mo,fy14_ms,fy14_mt,
    fy14_nc,fy14_nd,fy14_ne,fy14_nh,fy14_nj,fy14_nm,fy14_nv,fy14_ny,fy14_oh,fy14_ok,fy14_or,fy14_pa,fy14_pr,fy14_ri,
    fy14_sc,fy14_sd,fy14_tn,fy14_tx,fy14_ut,fy14_va,fy14_vt,fy14_wa,fy14_wi,fy14_wv,fy14_wy
]

FY_15_LIST=[
    fy15_ak,fy15_al,fy15_ar,fy15_az,fy15_ca,fy15_co,fy15_ct,fy15_dc,fy15_de,fy15_fl,fy15_ga,fy15_gu,fy15_hi,fy15_ia,
    fy15_id,fy15_il,fy15_in,fy15_ks,fy15_ky,fy15_la,fy15_ma,fy15_md,fy15_me,fy15_mi,fy15_mn,fy15_mo,fy15_ms,fy15_mt,
    fy15_nc,fy15_nd,fy15_ne,fy15_nh,fy15_nj,fy15_nm,fy15_nv,fy15_ny,fy15_oh,fy15_ok,fy15_or,fy15_pa,fy15_pr,fy15_ri,
    fy15_sc,fy15_sd,fy15_tn,fy15_tx,fy15_ut,fy15_va,fy15_vt,fy15_wa,fy15_wi,fy15_wv,fy15_wy
]

FY_16_LIST=[
    fy16_ak,fy16_al,fy16_ar,fy16_az,fy16_ca,fy16_co,fy16_ct,fy16_dc,fy16_de,fy16_fl,fy16_ga,fy16_gu,fy16_hi,fy16_ia,
    fy16_id,fy16_il,fy16_in,fy16_ks,fy16_ky,fy16_la,fy16_ma,fy16_md,fy16_me,fy16_mi,fy16_mn,fy16_mo,fy16_ms,fy16_mt,
    fy16_nc,fy16_nd,fy16_ne,fy16_nh,fy16_nj,fy16_nm,fy16_nv,fy16_ny,fy16_oh,fy16_ok,fy16_or,fy16_pa,fy16_pr,fy16_ri,
    fy16_sc,fy16_sd,fy16_tn,fy16_tx,fy16_ut,fy16_va,fy16_vt,fy16_wa,fy16_wi,fy16_wv,fy16_wy 
]

FY_14_SUMMARIES=[]
FY_15_SUMMARIES=[]
FY_16_SUMMARIES=[]

#What do I want to do with this information?
    #1. Gather number of veterans in a state
    #2. Gather number of dollars spent in that state
    #3. Find ratio of veterans to total spending in that state
    #4. Find total number of veterans
    #5. Find total number of dollars spent in total for each benefit
    #6. Find ratio of veterans to total spending on each benefit

FY_14_VETS_PER_STATE=[]
FY_15_VETS_PER_STATE=[]
FY_16_VETS_PER_STATE=[]

FY_14_DOLLARS_PER_STATE=[]
FY_15_DOLLARS_PER_STATE=[]
FY_16_DOLLARS_PER_STATE=[]

FY_14_VET_POP=0
FY_15_VET_POP=0
FY_16_VET_POP=0

FY_14_COMPENSATION=0
FY_15_COMPENSATION=0
FY_16_COMPENSATION=0

FY_14_EDUCATION=0
FY_15_EDUCATION=0
FY_16_EDUCATION=0

FY_14_INSURANCE=0
FY_15_INSURANCE=0
FY_16_INSURANCE=0

FY_14_MEDICAL=0
FY_15_MEDICAL=0
FY_16_MEDICAL=0

for state in FY_14_LIST:
    r=0
    for c in range(0,13):
        print(str(state[c]))
        #I know column two has a row that has the state name, so 
        #if state[2][row]==STATE_NAME
        #    I want state[3][row], state[5][row], state[7][row], state[10][row]
        

        if _line[2] in STATE_NAMES:
            FY_14_VETS_PER_STATE.append(_line[3])#1
            Dollars_spent_benefits=_line[5]+_line[7]+_line[10]+_line[11]
            FY_14_DOLLARS_PER_STATE.append(Dollars_spent_benefits)#2
            
            FY_14_VET_POP=FY_14_VET_POP+_line[3]#4
            FY_14_COMPENSATION=FY_14_COMPENSATION+_line[5]#5
            FY_14_EDUCATION=FY_14_EDUCATION+_line[7]#5
            FY_14_INSURANCE=FY_14_INSURANCE+_line[10]#5
            FY_14_MEDICAL=FY_14_MEDICAL+_line[11]#5
            
for x in range(0,53):
    ratio=float(FY_14_VETS_PER_STATE[x])/FY_14_DOLLARS_PER_STATE[x]
    FY_14_RATIO_PER_STATE[x]=ratio #3

for state in FY_15_LIST:
    for _line in state:
        if _line[2] in STATE_NAMES:
            FY_15_VETS_PER_STATE.append(_line[3])#1
            Dollars_spent_benefits=_line[5]+_line[7]+_line[10]+_line[11]
            FY_15_DOLLARS_PER_STATE.append(Dollars_spent_benefits)#2
            
            FY_15_VET_POP=FY_15_VET_POP+_line[3]#4
            FY_15_COMPENSATION=FY_15_COMPENSATION+_line[5]#5
            FY_15_EDUCATION=FY_15_EDUCATION+_line[7]#5
            FY_15_INSURANCE=FY_15_INSURANCE+_line[10]#5
            FY_15_MEDICAL=FY_15_MEDICAL+_line[11]#5
            
for x in range(0,53):
    ratio=float(FY_15_VETS_PER_STATE[x])/FY_15_DOLLARS_PER_STATE[x]
    FY_15_RATIO_PER_STATE[x]=ratio #3
    
for state in FY_16_LIST:
    for _line in state:
        if _line[2] in STATE_NAMES:
            FY_16_VETS_PER_STATE.append(_line[3])#1
            Dollars_spent_benefits=_line[5]+_line[7]+_line[10]+_line[11]
            FY_16_DOLLARS_PER_STATE.append(Dollars_spent_benefits)#2
            
            FY_16_VET_POP=FY_16_VET_POP+_line[3]#4
            FY_16_COMPENSATION=FY_16_COMPENSATION+_line[5]#5
            FY_16_EDUCATION=FY_16_EDUCATION+_line[7]#5
            FY_16_INSURANCE=FY_16_INSURANCE+_line[10]#5
            FY_16_MEDICAL=FY_16_MEDICAL+_line[11]#5
            
for x in range(0,53):
    ratio=float(FY_16_VETS_PER_STATE[x])/FY_16_DOLLARS_PER_STATE[x]
    FY_16_RATIO_PER_STATE[x]=ratio #3
'''  
#print(str(FY_14_RATIO_PER_STATE))

KeyError: 0

In [32]:
import csv

FY_14_FILE_NAMES=['fy14_ak.csv','fy14_al.csv','fy14_ar.csv','fy14_az.csv','fy14_ca.csv','fy14_co.csv','fy14_ct.csv',
                  'fy14_dc.csv','fy14_de.csv','fy14_fl.csv','fy14_ga.csv','fy14_gu.csv','fy14_hi.csv','fy14_ia.csv',
                  'fy14_id.csv','fy14_il.csv','fy14_in.csv','fy14_ks.csv','fy14_ky.csv','fy14_la.csv','fy14_ma.csv',
                  'fy14_md.csv','fy14_me.csv','fy14_mi.csv','fy14_mn.csv','fy14_mo.csv','fy14_ms.csv','fy14_mt.csv',
                  'fy14_nc.csv','fy14_nd.csv','fy14_ne.csv','fy14_nh.csv','fy14_nj.csv','fy14_nm.csv','fy14_nv.csv',
                  'fy14_ny.csv','fy14_oh.csv','fy14_ok.csv','fy14_or.csv','fy14_pa.csv','fy14_pr.csv','fy14_ri.csv',
                  'fy14_sc.csv','fy14_sd.csv','fy14_tn.csv','fy14_tx.csv','fy14_ut.csv','fy14_va.csv','fy14_vt.csv',
                  'fy14_wa.csv','fy14_wi.csv','fy14_wv.csv','fy14_wy.csv']

STATE_NAMES=['Alaska','Alabama','Arkansas','Arizona','California','Colorado','Connecticut','DC','Delaware','Florida',
            'Georgia','Guam','Hawaii','Iowa','Idaho','Illinois','Indiana','Kansas','Kentucky','Louisiana','Massachusetts',
            'Maryland', 'Maine','Michigan','Missouri','Mississippi','Montana','North Carolina','North Dakota','Nebraska',
            'New Hampshire','New Jersey','New Mexico','Nevada','New York','Ohio','Oklahoma','Oregon','Pennsylvania',
            'Puerto Rico','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Virginia','Vermont',
            'Washington','Wisconsin','West Virginia','Wyoming']

FY_14_VETS_PER_STATE=[]
FY_15_VETS_PER_STATE=[]
FY_16_VETS_PER_STATE=[]

FY_14_DOLLARS_PER_STATE=[]
FY_15_DOLLARS_PER_STATE=[]
FY_16_DOLLARS_PER_STATE=[]

FY_14_VET_POP=0
FY_15_VET_POP=0
FY_16_VET_POP=0

FY_14_COMPENSATION=0
FY_15_COMPENSATION=0
FY_16_COMPENSATION=0

FY_14_EDUCATION=0
FY_15_EDUCATION=0
FY_16_EDUCATION=0

FY_14_INSURANCE=0
FY_15_INSURANCE=0
FY_16_INSURANCE=0

FY_14_MEDICAL=0
FY_15_MEDICAL=0
FY_16_MEDICAL=0

#read from file row by row
#if row[2]=STATE NAME then gather the following
#    column 3, 5, 7, 10, 11

def gatherInfo(fname, state_name, year):
    global FY_14_VETS_PER_STATE=[]
    global FY_15_VETS_PER_STATE=[]
    global FY_16_VETS_PER_STATE=[]
    
    global FY_14_DOLLARS_PER_STATE=[]
    global FY_15_DOLLARS_PER_STATE=[]
    global FY_16_DOLLARS_PER_STATE=[]
    
    global FY_14_VET_POP=0
    global FY_15_VET_POP=0
    global FY_16_VET_POP=0
    
    global FY_14_COMPENSATION=0
    global FY_15_COMPENSATION=0
    global FY_16_COMPENSATION=0
    
    global FY_14_EDUCATION=0
    global FY_15_EDUCATION=0
    global FY_16_EDUCATION=0
    
    global FY_14_INSURANCE=0
    global FY_15_INSURANCE=0
    global FY_16_INSURANCE=0
    
    global FY_14_MEDICAL=0
    global FY_15_MEDICAL=0
    global FY_16_MEDICAL=0
    
    with open(fname, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            #print(str(row[2]))
            if '(Totals)' in str(row[2]):
                if year==14:
                    FY_14_VETS_PER_STATE.append(_line[3])#1
                    Dollars_spent_benefits=_line[5]+_line[7]+_line[10]+_line[11]
                    FY_14_DOLLARS_PER_STATE.append(Dollars_spent_benefits)#2
            
                    FY_14_VET_POP=FY_14_VET_POP+_line[3]#4
                    FY_14_COMPENSATION=FY_14_COMPENSATION+_line[5]#5
                    FY_14_EDUCATION=FY_14_EDUCATION+_line[7]#5
                    FY_14_INSURANCE=FY_14_INSURANCE+_line[10]#5
                    FY_14_MEDICAL=FY_14_MEDICAL+_line[11]#5
    return 0

if __name__=="__main__":
    FY_14_FILE_NAMES=['fy14_ak.csv','fy14_al.csv','fy14_ar.csv','fy14_az.csv','fy14_ca.csv','fy14_co.csv','fy14_ct.csv',
                  'fy14_dc.csv','fy14_de.csv','fy14_fl.csv','fy14_ga.csv','fy14_gu.csv','fy14_hi.csv','fy14_ia.csv',
                  'fy14_id.csv','fy14_il.csv','fy14_in.csv','fy14_ks.csv','fy14_ky.csv','fy14_la.csv','fy14_ma.csv',
                  'fy14_md.csv','fy14_me.csv','fy14_mi.csv','fy14_mn.csv','fy14_mo.csv','fy14_ms.csv','fy14_mt.csv',
                  'fy14_nc.csv','fy14_nd.csv','fy14_ne.csv','fy14_nh.csv','fy14_nj.csv','fy14_nm.csv','fy14_nv.csv',
                  'fy14_ny.csv','fy14_oh.csv','fy14_ok.csv','fy14_or.csv','fy14_pa.csv','fy14_pr.csv','fy14_ri.csv',
                  'fy14_sc.csv','fy14_sd.csv','fy14_tn.csv','fy14_tx.csv','fy14_ut.csv','fy14_va.csv','fy14_vt.csv',
                  'fy14_wa.csv','fy14_wi.csv','fy14_wv.csv','fy14_wy.csv']
    STATE_NAMES=['Alaska','Alabama','Arkansas','Arizona','California','Colorado','Connecticut',
                 'DC','Delaware','Florida','Georgia','Guam','Hawaii','Iowa',
                 'Idaho','Illinois','Indiana','Kansas','Kentucky','Louisiana','Maine',
                 'Massachusetts','Maryland', 'Maine','Michigan','Missouri','Mississippi','Montana',
                 'North Carolina','North Dakota','Nebraska','New Hampshire','New Jersey','New Mexico','Nevada',
                 'New York','Ohio','Oklahoma','Oregon','Pennsylvania','Puerto Rico','Rhode Island',
                 'South Carolina','South Dakota','Tennessee','Texas','Utah','Virginia','Vermont',
                 'Washington','Wisconsin','West Virginia','Wyoming']
    i=0
    for file_name in FY_14_FILE_NAMES:
        state_name=STATE_NAMES[i]
        gatherInfo(file_name, state_name)
        i=i+1

['14', 'AK', 'ALASKA (Totals)', '73,397', '$552,280 ', '$244,437 ', '$165 ', '$74,731 ', ' $- ', '$6,154 ', '$3,855 ', '$222,938 ', '18,182']
['14', 'AK', 'ALASKA (Totals)', '73,397', '$552,280 ', '$244,437 ', '$165 ', '$74,731 ', ' $- ', '$6,154 ', '$3,855 ', '$222,938 ', '18,290']
['14', 'AL', 'ALABAMA (Totals)', '413,618', '$3,191,317 ', '$1,875,091 ', '$4,992 ', '$225,325 ', ' $- ', '$35,140 ', '$29,054 ', '$1,021,715 ', '110,616']
['14', 'AL', 'ALABAMA (Totals)', '413,618', '$3,191,317 ', '$1,875,091 ', '$4,992 ', '$225,325 ', ' $- ', '$35,140 ', '$29,054 ', '$1,021,715 ', '110,616']
['14', 'AR', 'ARKANSAS (Totals)', '249,274', '$2,143,834 ', '$1,055,813 ', '$7,143 ', '$95,186 ', ' $- ', '$29,631 ', '$15,816 ', '$940,246 ', '86,718']
['14', 'AR', 'ARKANSAS (Totals)', '249,274', '$2,143,834 ', '$1,055,813 ', '$7,143 ', '$95,186 ', ' $- ', '$29,631 ', '$15,816 ', '$940,246 ', '86,718']
['14', 'AZ', 'ARIZONA (Totals)', '532,206', '$3,607,036 ', '$1,666,170 ', '$15,452 ', '$410,041 ', ' $- ', '$107,135 ', '$33,149 ', '$1,375,088 ', '143,785']
['14', 'AZ', 'ARIZONA (Totals)', '532,206', '$3,607,036 ', '$1,666,170 ', '$15,452 ', '$410,041 ', ' $- ', '$107,135 ', '$33,149 ', '$1,375,088 ', '143,785']
['14', 'CA', 'CALIFORNIA (Totals)', '1,851,470', '$14,318,281 ', '$6,376,052 ', '$153,525 ', '$1,848,364 ', ' $- ', '$197,940 ', '$157,549 ', '$5,584,851 ', '460,954']
['14', 'CA', 'CALIFORNIA (Totals)', '1,851,470', '$14,318,281 ', '$6,376,052 ', '$153,525 ', '$1,848,364 ', ' $- ', '$197,940 ', '$157,549 ', '$5,584,851 ', '460,954']
['14', 'CO', 'COLORADO (Totals)', '413,271', '$3,073,039 ', '$1,447,416 ', '$221,644 ', '$379,047 ', ' $- ', '$61,079 ', '$32,291 ', '$931,562 ', '95,382']
['14', 'CO', 'COLORADO (Totals)', '413,271', '$3,073,039 ', '$1,447,416 ', '$221,644 ', '$379,047 ', ' $- ', '$61,079 ', '$32,291 ', '$931,562 ', '95,382']
['14', 'CT', 'CONNECTICUT (Totals)', '213,420', '$1,171,099 ', '$432,271 ', '$403 ', '$106,709 ', ' $- ', '$14,238 ', '$24,166 ', '$593,312 ', '51,073']
['14', 'CT', 'CONNECTICUT (Totals)', '213,420', '$1,171,099 ', '$432,271 ', '$403 ', '$106,709 ', ' $- ', '$14,238 ', '$24,166 ', '$593,312 ', '51,073']
['14', 'DC', 'DC (Totals)', '29,825', '$2,703,410 ', '$90,387 ', '$257,897 ', '$35,086 ', ' $- ', '$2,091,541 ', '$3,094 ', '$225,406 ', '8,598']
['14', 'DC', 'DC (Totals)', '29,825', '$2,703,410 ', '$90,387 ', '$257,897 ', '$35,086 ', ' $- ', '$2,091,541 ', '$3,094 ', '$225,406 ', '8,598']
['14', 'DE', 'DELAWARE (Totals)', '78,099', '$398,842 ', '$199,732 ', '$693 ', '$38,126 ', ' $- ', '$3,792 ', '$5,711 ', '$150,788 ', '15,000']
['14', 'DE', 'DELAWARE (Totals)', '78,099', '$398,842 ', '$199,732 ', '$693 ', '$38,126 ', ' $- ', '$3,792 ', '$5,711 ', '$150,788 ', '15,000']
['14', 'FL', 'FLORIDA (Totals)', '1,583,697', '$11,688,201 ', '$5,618,726 ', '$80,833 ', '$1,043,675 ', ' $- ', '$149,942 ', '$132,732 ', '$4,662,293 ', '493,890']
['14', 'FL', 'FLORIDA (Totals)', '1,583,697', '$11,688,201 ', '$5,618,726 ', '$80,833 ', '$1,043,675 ', ' $- ', '$149,942 ', '$132,732 ', '$4,662,293 ', '493,890']
['14', 'GA', 'GEORGIA (Totals)', '752,882', '$5,398,211 ', '$3,004,840 ', '$1,056 ', '$528,777 ', ' $- ', '$106,881 ', '$48,836 ', '$1,707,821 ', '189,127']
['14', 'GA', 'GEORGIA (Totals)', '752,882', '$5,398,211 ', '$3,004,840 ', '$1,056 ', '$528,777 ', ' $- ', '$106,881 ', '$48,836 ', '$1,707,821 ', '189,127']
['14', 'GU', 'Guam (Totals)', '9,453', '$88,631 ', '$51,981 ', ' $- ', '$15,389 ', ' $- ', ' $- ', '$832 ', '$20,430 ', '2,584', '']
['14', 'HI', 'HAWAII (Totals)', '121,007', '$842,115 ', '$388,532 ', '$573 ', '$167,447 ', ' $- ', '$16,593 ', '$14,822 ', '$254,149 ', '25,041']
['14', 'HI', 'HAWAII (Totals)', '121,007', '$842,115 ', '$388,532 ', '$573 ', '$167,447 ', ' $- ', '$16,593 ', '$14,822 ', '$254,149 ', '25,041']
['14', 'IA', 'IOWA (Totals)', '231,655', '$1,339,350 ', '$592,671 ', '$379 ', '$78,530 ', ' $- ', '$11,156 ', '$18,393 ', '$638,221 ', '72,367']
['14', 'IA', 'IOWA (Totals)', '231,655', '$1,339,350 ', '$592,671 ', '$379 ', '$78,530 ', ' $- ', '$11,156 ', '$18,393 ', '$638,221 ', '72,367']
['14', 'ID', 'IDAHO (Totals)', '132,395', '$827,990 ', '$401,211 ', '$995 ', '$58,612 ', ' $- ', '$8,180 ', '$7,587 ', '$351,404 ', '41,266']
['14', 'ID', 'IDAHO (Totals)', '132,395', '$827,990 ', '$401,211 ', '$995 ', '$58,612 ', ' $- ', '$8,180 ', '$7,587 ', '$351,404 ', '41,266']
['14', 'IL', 'ILLINOIS (Totals)', '721,575', '$4,248,086 ', '$1,680,632 ', '$17,019 ', '$349,069 ', ' $- ', '$49,986 ', '$62,953 ', '$2,088,426 ', '182,101']
['14', 'IL', 'ILLINOIS (Totals)', '721,575', '$4,248,086 ', '$1,680,632 ', '$17,019 ', '$349,069 ', ' $- ', '$49,986 ', '$62,953 ', '$2,088,426 ', '182,101']
['14', 'IN', 'INDIANA (Totals)', '476,283', '$2,667,905 ', '$1,239,688 ', '$1,549 ', '$165,293 ', ' $- ', '$50,029 ', '$24,944 ', '$1,186,402 ', '129,308']
['14', 'IN', 'INDIANA (Totals)', '476,283', '$2,667,910 ', '$1,239,691 ', '$1,549 ', '$165,293 ', ' $- ', '$50,029 ', '$24,944 ', '$1,186,403 ', '129,308']
['14', 'KS', 'KANSAS (Totals)', '221,206', '$1,358,491 ', '$632,709 ', '$270 ', '$113,362 ', ' $- ', '$25,295 ', '$16,883 ', '$569,972 ', '58,490']
['14', 'KS', 'KANSAS (Totals)', '221,206', '$1,358,491 ', '$632,709 ', '$270 ', '$113,362 ', ' $- ', '$25,295 ', '$16,883 ', '$569,972 ', '58,490']
['14', 'KY', 'KENTUCKY (Totals)', '330,599', '$2,425,358 ', '$1,255,748 ', '$10,245 ', '$155,455 ', ' $- ', '$40,024 ', '$18,858 ', '$945,028 ', '101,840']
['14', 'KY', 'KENTUCKY (Totals)', '330,599', '$2,425,358 ', '$1,255,748 ', '$10,245 ', '$155,455 ', ' $- ', '$40,024 ', '$18,858 ', '$945,028 ', '101,840']
['14', 'LA', 'LOUISIANA (Totals)', '330,145', '$2,540,466 ', '$1,211,754 ', '$260,204 ', '$146,468 ', ' $- ', '$26,158 ', '$20,187 ', '$875,694 ', '88,621']
['14', 'LA', 'LOUISIANA (Totals)', '330,145', '$2,540,466 ', '$1,211,754 ', '$260,204 ', '$146,468 ', ' $- ', '$26,158 ', '$20,187 ', '$875,694 ', '88,621']
['14', 'MA', 'MASSACHUSETTS (Totals)', '379,772', '$2,593,152 ', '$1,159,009 ', '$5,712 ', '$209,261 ', ' $- ', '$29,524 ', '$43,491 ', '$1,146,155 ', '83,926']
['14', 'MA', 'MASSACHUSETTS (Totals)', '379,772', '$2,593,152 ', '$1,159,009 ', '$5,712 ', '$209,261 ', ' $- ', '$29,524 ', '$43,491 ', '$1,146,155 ', '83,926']
['14', 'MD', 'MARYLAND (Totals)', '437,762', '$2,688,111 ', '$1,228,854 ', '$5,299 ', '$364,342 ', ' $- ', '$23,589 ', '$38,630 ', '$1,027,397 ', '82,383']
['14', 'MD', 'MARYLAND (Totals)', '437,762', '$2,688,111 ', '$1,228,854 ', '$5,299 ', '$364,342 ', ' $- ', '$23,589 ', '$38,630 ', '$1,027,397 ', '82,383']
['14', 'ME', 'MAINE (Totals)', '127,234', '$959,396 ', '$541,754 ', '$126 ', '$45,924 ', ' $- ', '$18,616 ', '$8,733 ', '$344,244 ', '39,859']
['14', 'ME', 'MAINE (Totals)', '127,234', '$959,396 ', '$541,754 ', '$126 ', '$45,924 ', ' $- ', '$18,616 ', '$8,733 ', '$344,244 ', '39,859']
['14', 'MI', 'MICHIGAN (Totals)', '658,469', '$3,753,563 ', '$1,983,451 ', '$17,517 ', '$232,514 ', ' $- ', '$52,983 ', '$46,116 ', '$1,420,982 ', '150,215']
['14', 'MI', 'MICHIGAN (Totals)', '658,469', '$3,753,559 ', '$1,983,447 ', '$17,517 ', '$232,513 ', ' $- ', '$52,983 ', '$46,116 ', '$1,420,982 ', '150,215']
['14', 'MN', 'MINNESOTA (Totals)', '369,149', '$2,564,646 ', '$1,146,384 ', '$16,225 ', '$151,587 ', ' $- ', '$83,322 ', '$30,815 ', '$1,136,313 ', '115,827']
['14', 'MN', 'MINNESOTA (Totals)', '369,149', '$2,564,646 ', '$1,146,384 ', '$16,225 ', '$151,587 ', ' $- ', '$83,322 ', '$30,815 ', '$1,136,313 ', '115,827']
['14', 'MO', 'MISSOURI (Totals)', '494,346', '$3,440,223 ', '$1,651,755 ', '$79,828 ', '$209,426 ', ' $- ', '$154,455 ', '$32,728 ', '$1,312,031 ', '139,929']
['14', 'MO', 'MISSOURI (Totals)', '494,346', '$3,440,223 ', '$1,651,755 ', '$79,828 ', '$209,426 ', ' $- ', '$154,455 ', '$32,728 ', '$1,312,031 ', '139,929']
['14', 'MS', 'MISSISSIPPI (Totals)', '220,389', '$1,657,042 ', '$776,679 ', '$36,478 ', '$100,467 ', ' $- ', '$30,094 ', '$14,544 ', '$698,780 ', '69,754']
['14', 'MS', 'MISSISSIPPI (Totals)', '220,389', '$1,657,042 ', '$776,679 ', '$36,478 ', '$100,467 ', ' $- ', '$30,094 ', '$14,544 ', '$698,780 ', '69,754']
['14', 'MT', 'MONTANA (Totals)', '99,646', '$731,755 ', '$335,093 ', '$250 ', '$42,166 ', ' $- ', '$8,088 ', '$7,950 ', '$338,208 ', '35,966']
['14', 'MT', 'MONTANA (Totals)', '99,646', '$731,755 ', '$335,093 ', '$250 ', '$42,166 ', ' $- ', '$8,088 ', '$7,950 ', '$338,208 ', '35,966']
['14', 'NC', 'NORTH CAROLINA (Totals)', '775,020', '$5,949,873 ', '$3,328,183 ', '$8,405 ', '$478,939 ', ' $- ', '$93,726 ', '$53,403 ', '$1,987,216 ', '214,278']
['14', 'NC', 'NORTH CAROLINA (Totals)', '775,020', '$5,949,873 ', '$3,328,183 ', '$8,405 ', '$478,939 ', ' $- ', '$93,726 ', '$53,403 ', '$1,987,216 ', '214,278']
['14', 'ND', 'NORTH DAKOTA (Totals)', '57,395', '$367,003 ', '$171,165 ', '$3,970 ', '$25,528 ', ' $- ', '$6,508 ', '$4,156 ', '$155,677 ', '18,988']
['14', 'ND', 'NORTH DAKOTA (Totals)', '57,395', '$367,003 ', '$171,165 ', '$3,970 ', '$25,528 ', ' $- ', '$6,508 ', '$4,156 ', '$155,677 ', '18,988']
['14', 'NE', 'NEBRASKA (Totals)', '143,375', '$1,136,146 ', '$557,741 ', '$9,147 ', '$70,254 ', ' $- ', '$36,827 ', '$13,012 ', '$449,167 ', '47,352']
['14', 'NE', 'NEBRASKA (Totals)', '143,375', '$1,136,146 ', '$557,741 ', '$9,147 ', '$70,254 ', ' $- ', '$36,827 ', '$13,012 ', '$449,167 ', '47,352']
['14', 'NH', 'NEW HAMPSHIRE (Totals)', '113,660', '$674,052 ', '$311,022 ', '$3,744 ', '$58,392 ', ' $- ', '$6,000 ', '$8,979 ', '$285,915 ', '28,969']
['14', 'NH', 'NEW HAMPSHIRE (Totals)', '113,660', '$674,052 ', '$311,022 ', '$3,744 ', '$58,392 ', ' $- ', '$6,000 ', '$8,979 ', '$285,915 ', '28,969']
['14', 'NJ', 'NEW JERSEY (Totals)', '428,396', '$2,115,578 ', '$1,047,058 ', '$555 ', '$214,108 ', ' $- ', '$18,716 ', '$51,045 ', '$784,096 ', '77,128']
['14', 'NJ', 'NEW JERSEY (Totals)', '428,396', '$2,115,578 ', '$1,047,058 ', '$555 ', '$214,108 ', ' $- ', '$18,716 ', '$51,045 ', '$784,096 ', '77,128']
['14', 'NM', 'NEW MEXICO (Totals)', '171,528', '$1,450,002 ', '$794,229 ', '$11,767 ', '$79,524 ', ' $- ', '$12,854 ', '$11,087 ', '$540,540 ', '51,702']
['14', 'NM', 'NEW MEXICO (Totals)', '171,528', '$1,450,002 ', '$794,229 ', '$11,767 ', '$79,524 ', ' $- ', '$12,854 ', '$11,087 ', '$540,540 ', '51,702']
['14', 'NV', 'NEVADA (Totals)', '228,027', '$1,780,651 ', '$776,443 ', '$50,831 ', '$108,908 ', ' $- ', '$12,870 ', '$13,406 ', '$818,193 ', '69,464']
['14', 'NV', 'NEVADA (Totals)', '228,027', '$1,780,651 ', '$776,443 ', '$50,831 ', '$108,908 ', ' $- ', '$12,870 ', '$13,406 ', '$818,193 ', '69,464']
['14', 'NY', 'NEW YORK (Totals)', '892,221', '$6,123,810 ', '$2,396,837 ', '$30,504 ', '$548,240 ', ' $- ', '$124,442 ', '$92,821 ', '$2,930,966 ', '230,159']
['14', 'NY', 'NEW YORK (Totals)', '892,221', '$6,123,810 ', '$2,396,837 ', '$30,504 ', '$548,240 ', ' $- ', '$124,442 ', '$92,821 ', '$2,930,966 ', '230,159']
['14', 'OH', 'OHIO (Totals)', '866,481', '$7,504,281 ', '$2,235,023 ', '$21,382 ', '$324,969 ', ' $- ', '$2,549,868 ', '$56,928 ', '$2,316,111 ', '230,266']
['14', 'OH', 'OHIO (Totals)', '866,481', '$7,504,281 ', '$2,235,023 ', '$21,382 ', '$324,969 ', ' $- ', '$2,549,868 ', '$56,928 ', '$2,316,111 ', '230,266']
['14', 'OK', 'OKLAHOMA (Totals)', '337,571', '$2,934,748 ', '$1,823,983 ', '$4,905 ', '$155,650 ', ' $- ', '$121,169 ', '$20,467 ', '$808,574 ', '92,674']
['14', 'OK', 'OKLAHOMA (Totals)', '337,571', '$2,934,748 ', '$1,823,983 ', '$4,905 ', '$155,650 ', ' $- ', '$121,169 ', '$20,467 ', '$808,574 ', '92,674']
['14', 'OR', 'OREGON (Totals)', '331,632', '$2,542,834 ', '$1,282,449 ', '$19,124 ', '$142,348 ', ' $- ', '$35,597 ', '$23,413 ', '$1,039,903 ', '99,502']
['14', 'OR', 'OREGON (Totals)', '331,632', '$2,542,834 ', '$1,282,449 ', '$19,124 ', '$142,348 ', ' $- ', '$35,597 ', '$23,413 ', '$1,039,903 ', '99,502']
['14', 'PA', 'PENNSYLVANIA (Totals)', '939,069', '$5,260,391 ', '$2,432,807 ', '$19,992 ', '$376,417 ', ' $- ', '$158,371 ', '$79,167 ', '$2,193,637 ', '233,551']
['14', 'PA', 'PENNSYLVANIA (Totals)', '939,069', '$5,260,391 ', '$2,432,807 ', '$19,992 ', '$376,417 ', ' $- ', '$158,371 ', '$79,167 ', '$2,193,637 ', '233,551']
['14', 'PR', 'Puerto Rico (Totals)', '93,240', '$1,563,237 ', '$816,544 ', '$17,830 ', '$65,064 ', ' $- ', '$22,157 ', '$2,832 ', '$638,810 ', '57,248']
['14', 'RI', 'RHODE ISLAND (Totals)', '71,966', '$529,503 ', '$232,604 ', '$3,355 ', '$40,498 ', ' $- ', '$21,115 ', '$6,221 ', '$225,710 ', '19,954']
['14', 'RI', 'RHODE ISLAND (Totals)', '71,966', '$529,503 ', '$232,604 ', '$3,355 ', '$40,498 ', ' $- ', '$21,115 ', '$6,221 ', '$225,710 ', '19,954']
['14', 'SC', 'SOUTH CAROLINA (Totals)', '417,554', '$3,289,095 ', '$1,868,959 ', '$10,942 ', '$267,185 ', ' $- ', '$65,216 ', '$31,415 ', '$1,045,378 ', '127,365']
['14', 'SC', 'SOUTH CAROLINA (Totals)', '417,554', '$3,289,095 ', '$1,868,959 ', '$10,942 ', '$267,185 ', ' $- ', '$65,216 ', '$31,415 ', '$1,045,378 ', '127,365']
['14', 'SD', 'SOUTH DAKOTA (Totals)', '72,030', '$619,864 ', '$238,175 ', '$3,531 ', '$31,787 ', ' $- ', '$11,593 ', '$6,103 ', '$328,675 ', '29,827']
['14', 'SD', 'SOUTH DAKOTA (Totals)', '72,030', '$619,864 ', '$238,175 ', '$3,531 ', '$31,787 ', ' $- ', '$11,593 ', '$6,103 ', '$328,675 ', '29,827']
['14', 'TN', 'TENNESSEE (Totals)', '506,340', '$3,758,888 ', '$1,995,305 ', '$6,028 ', '$269,071 ', ' $- ', '$63,217 ', '$32,085 ', '$1,393,181 ', '140,625']
['14', 'TN', 'TENNESSEE (Totals)', '506,340', '$3,758,888 ', '$1,995,305 ', '$6,028 ', '$269,071 ', ' $- ', '$63,217 ', '$32,085 ', '$1,393,181 ', '140,625']
['14', 'TX', 'TEXAS (Totals)', '1,680,418', '$15,394,005 ', '$7,282,260 ', '$28,798 ', '$1,357,830 ', '$2,046,206 ', '$223,667 ', '$110,141 ', '$4,345,103 ', '446,303']
['14', 'TX', 'TEXAS (Totals)', '1,680,418', '$15,394,005 ', '$7,282,260 ', '$28,798 ', '$1,357,830 ', '$2,046,206 ', '$223,667 ', '$110,141 ', '$4,345,103 ', '446,303']
['14', 'UT', 'UTAH (Totals)', '151,719', '$1,029,344 ', '$433,073 ', '$2,156 ', '$120,457 ', ' $- ', '$56,947 ', '$11,521 ', '$405,189 ', '35,142']
['14', 'UT', 'UTAH (Totals)', '151,719', '$1,029,344 ', '$433,073 ', '$2,156 ', '$120,457 ', ' $- ', '$56,947 ', '$11,521 ', '$405,189 ', '35,142']
['14', 'VA', 'VIRGINIA (Totals)', '781,388', '$5,250,562 ', '$2,729,280 ', '$21,218 ', '$931,880 ', ' $- ', '$63,300 ', '$62,360 ', '$1,443,669 ', '148,585']
['14', 'VA', 'VIRGINIA (Totals)', '781,388', '$5,251,707 ', '$2,729,280 ', '$21,218 ', '$931,880 ', ' $- ', '$63,300 ', '$62,360 ', '$1,443,669 ', '148,585']
['14', 'VT', 'VERMONT (Totals)', '48,602', '$295,362 ', '$135,803 ', '$1,560 ', '$20,321 ', ' $- ', '$3,796 ', '$3,155 ', '$130,727 ', '14,919']
['14', 'VT', 'VERMONT (Totals)', '48,602', '$295,362 ', '$135,803 ', '$1,560 ', '$20,321 ', ' $- ', '$3,796 ', '$3,155 ', '$130,727 ', '14,919']
['14', 'WA', 'WASHINGTON (Totals)', '603,623', '$3,811,479 ', '$2,070,141 ', '$33,346 ', '$392,247 ', ' $- ', '$71,074 ', '$41,739 ', '$1,202,932 ', '124,006']
['14', 'WA', 'WASHINGTON (Totals)', '603,623', '$3,811,479 ', '$2,070,141 ', '$33,346 ', '$392,247 ', ' $- ', '$71,074 ', '$41,739 ', '$1,202,932 ', '124,006']
['14', 'WI', 'WISCONSIN (Totals)', '413,723', '$2,665,107 ', '$1,142,091 ', '$11,984 ', '$143,544 ', ' $- ', '$70,816 ', '$33,242 ', '$1,263,430 ', '120,515']
['14', 'WI', 'WISCONSIN (Totals)', '413,723', '$2,665,100 ', '$1,142,084 ', '$11,984 ', '$143,543 ', ' $- ', '$70,816 ', '$33,242 ', '$1,263,430 ', '120,515']
['14', 'WV', 'WEST VIRGINIA (Totals)', '167,355', '$1,826,167 ', '$722,958 ', '$9,927 ', '$49,784 ', ' $- ', '$318,791 ', '$8,505 ', '$716,202 ', '59,261']
['14', 'WV', 'WEST VIRGINIA (Totals)', '167,355', '$1,826,167 ', '$722,958 ', '$9,927 ', '$49,784 ', ' $- ', '$318,791 ', '$8,505 ', '$716,202 ', '59,261']
['14', 'WY', 'WYOMING (Totals)', '49,708', '$383,891 ', '$152,461 ', '$4,144 ', '$17,544 ', ' $- ', '$1,623 ', '$2,710 ', '$205,410 ', '18,730']
['14', 'WY', 'WYOMING (Totals)', '49,708', '$383,891 ', '$152,461 ', '$4,144 ', '$17,544 ', ' $- ', '$1,623 ', '$2,710 ', '$205,410 ', '18,730']